
export const COUNTRIES = [
    { label: 'Nigeria', value: 'Nigeria', dialCode: '+234', code: 'ng' },
    { label: 'United States', value: 'United States', dialCode: '+1', code: 'us' },
    { label: 'United Kingdom', value: 'United Kingdom', dialCode: '+44', code: 'gb' },
    { label: 'Ghana', value: 'Ghana', dialCode: '+233', code: 'gh' },
    { label: 'Kenya', value: 'Kenya', dialCode: '+254', code: 'ke' },
    { label: 'South Africa', value: 'South Africa', dialCode: '+27', code: 'za' },
    { label: 'Canada', value: 'Canada', dialCode: '+1', code: 'ca' },
    { label: 'India', value: 'India', dialCode: '+91', code: 'in' },
    { label: 'Germany', value: 'Germany', dialCode: '+49', code: 'de' },
    { label: 'France', value: 'France', dialCode: '+33', code: 'fr' },
    { label: 'UAE', value: 'UAE', dialCode: '+971', code: 'ae' },
    { label: 'Saudi Arabia', value: 'Saudi Arabia', dialCode: '+966', code: 'sa' },
    { label: 'Cameroon', value: 'Cameroon', dialCode: '+237', code: 'cm' },
    { label: 'Cote d\'Ivoire', value: 'Cote d\'Ivoire', dialCode: '+225', code: 'ci' },
    { label: 'Benin', value: 'Benin', dialCode: '+229', code: 'bj' },
    { label: 'Togo', value: 'Togo', dialCode: '+228', code: 'tg' },
    { label: 'Senegal', value: 'Senegal', dialCode: '+221', code: 'sn' },
    { label: 'Ethiopia', value: 'Ethiopia', dialCode: '+251', code: 'et' },
    { label: 'Egypt', value: 'Egypt', dialCode: '+20', code: 'eg' },
    { label: 'Australia', value: 'Australia', dialCode: '+61', code: 'au' },
    { label: 'China', value: 'China', dialCode: '+86', code: 'cn' },
    { label: 'Brazil', value: 'Brazil', dialCode: '+55', code: 'br' },
];
