
export const COMMON_SERVICES = {
  general: [
    'General Consultation',
    'Follow-up Visit',
    'Emergency Care',
    'Diagnostic Test',
    'Pharmacy / Medication',
    'Vaccination',
    'Physical Examination',
    'Diagnostic Imaging (X-Ray/Scan)',
    'Medical Report',
    'CLINICAL TREATMENT PLAN'
  ],
  hospital: [
    'Inpatient Admission',
    'ICU Services',
    'Triage & Emergency',
    'Surgical Operation',
    'Radiology & Diagnostics',
    'Antenatal Care'
  ],
  pharmacy: [
    'Prescription Dispensing',
    'Over-The-Counter Medication',
    'Blood Pressure Check',
    'Blood Glucose Monitoring',
    'Consultation with Pharmacist'
  ],
  diagnostic: [
    'Full Blood Count',
    'Urinalysis',
    'Lipid Profile',
    'Thyroid Function Test',
    'Malaria Parasite Test',
    'COVID-19 Testing'
  ],
  doctor: [
    'Specialist Consultation',
    'Surgical Procedure',
    'Medical Report Issuance',
    'Prescription Renewal',
    'Chronic Disease Management',
    'Cancer Screening',
    'Prenatal Care',
    'Post-Natal Care'
  ],
  nurse: [
    'Wound Care & Dressing',
    'IV Medication Administration',
    'Vital Signs Monitoring',
    'Catheter Insertion/Care',
    'Home Nursing Visit',
    'Elderly Care Assistance',
    'Child Immunization',
    'Health Education'
  ],
  biotech_engineer: [
    'Equipment Installation & Setup',
    'Maintenance & Repair',
    'Safety & Risk Management',
    'Technical Support for Clinical Staff',
    'Training on Equipment Use',
    'Equipment Procurement Selection',
    'Technology Planning',
    'Documentation & Records',
    'Upgrades & System Integration'
  ]
};

export const SPECIALTY_SERVICES: Record<string, string[]> = {
  'Cardiologist': [
    'Cardiovascular risk assessment',
    'Heart health check-up',
    'Lifestyle counseling',
    'Hypertension management',
    'Hyperlipidemia management',
    'History/physical exam',
    'Lab test interpretation',
    'Electrocardiography (ECG)',
    'Ambulatory ECG monitoring',
    'Stress testing',
    'Echocardiography (TTE/TEE)',
    'Cardiac stress imaging',
    'Cardiac CT',
    'Cardiac MRI',
    'Coronary artery disease management',
    'Acute coronary syndrome care',
    'Heart failure management',
    'Valvular heart disease management',
    'Arrhythmia diagnosis',
    'Arrhythmia drug management',
    'Device follow-up',
    'Cardiac catheterization',
    'Coronary angiography',
    'Percutaneous coronary intervention (PCI)',
    'Pacemaker implantation',
    'ICD implantation',
    'Cardiac ablation',
    'Electrical cardioversion',
    'Chronic disease follow-up',
    'Cardiac rehabilitation coordination',
    'Surgical coordination',
    'Other'
  ],
  'Dermatologist': [
    'Skin examination',
    'Medical history',
    'Inflammatory disease diagnosis',
    'Infectious disease diagnosis',
    'Skin cancer risk evaluation',
    'Skin biopsy',
    'Dermatoscopy',
    'Patch testing',
    'KOH microscopy',
    'Acne management',
    'Rosacea treatment',
    'Eczema management',
    'Psoriasis treatment',
    'Skin infection management',
    'Ulcer care',
    'Blistering disorder treatment',
    'Skin cancer screening',
    'Actinic keratosis treatment',
    'Skin tumor excision',
    'Mohs surgery',
    'Hair loss treatment',
    'Scalp disease management',
    'Nail disorder treatment',
    'Pigmentation management',
    'Chemical peel',
    'Laser therapy',
    'Sclerotherapy',
    'Cryosurgery',
    'Electrosurgery',
    'Mole removal',
    'Scar revision',
    'Sun protection counseling',
    'Cosmetic product counseling',
    'Specialist coordination',
    'Other'
  ],
  'Neurologist': [
    'Neurological history/exam',
    'Outpatient consultation',
    'Second-opinion review',
    'Stroke management',
    'Epilepsy management',
    'Movement disorder management',
    'Dementia management',
    'Neuromuscular disease management',
    'Multiple sclerosis management',
    'Headache management',
    'Sleep disorder management',
    'Neuroinfectious disease management',
    'Neuro-oncology management',
    'Imaging interpretation',
    'EEG monitoring',
    'Nerve conduction studies',
    'EMG',
    'Lumbar puncture',
    'Autonomic testing',
    'Skin/muscle biopsy',
    'Botulinum toxin injection',
    'Endovascular intervention',
    'Intraoperative monitoring',
    'Chronic disease monitoring',
    'Multidisciplinary coordination',
    'Brain death evaluation',
    'Other'
  ],
  'Psychiatrist': [
    'Psychiatric evaluation',
    'Biopsychosocial assessment',
    'Diagnosis',
    'Medical history review',
    'Mental status examination',
    'Psychological testing',
    'Laboratory test ordering',
    'Physical examination',
    'Differential diagnosis',
    'Medication prescription',
    'Medication management',
    'Psychopharmacology',
    'Side effect monitoring',
    'Drug interaction review',
    'Antidepressant prescription',
    'Mood stabilizer prescription',
    'Antipsychotic prescription',
    'Anxiolytic prescription',
    'Stimulant prescription',
    'Psychotherapy',
    'Cognitive behavioral therapy (CBT)',
    'Dialectical behavior therapy (DBT)',
    'Interpersonal therapy',
    'Psychodynamic therapy',
    'Supportive counseling',
    'Trauma-informed therapy',
    'Family therapy',
    'Couples therapy',
    'Crisis intervention',
    'Suicide risk assessment',
    'Safety planning',
    'Electroconvulsive therapy (ECT)',
    'Transcranial magnetic stimulation (TMS)',
    'Ketamine therapy',
    'Inpatient care',
    'Outpatient care',
    'Partial hospitalization',
    'Long term care',
    'Relapse prevention',
    'Lifestyle counseling',
    'Sleep hygiene education',
    'Stress management',
    'Consultation-liaison psychiatry',
    'Forensic psychiatry',
    'Geriatric psychiatry',
    'Addiction psychiatry',
    'Child psychiatry',
    'Psychosocial rehabilitation',
    'Support group referral',
    'Treatment planning',
    'Telepsychiatry',
    'Psychoeducation',
    'Behavioral intervention',
    'Medication adjustment',
    'Court-ordered evaluation',
    'Other'
  ],
  'Pediatrician': [
    'Well-child visit',
    'Immunization administration',
    'Nutrition counseling',
    'Anticipatory guidance',
    'Sports physical',
    'Developmental assessment',
    'ADHD management',
    'Behavioral counseling',
    'Special needs support',
    'Acute illness management',
    'GI illness care',
    'Skin infection treatment',
    'Minor injury care',
    'Febrile illness workup',
    'Asthma management',
    'Epilepsy follow-up',
    'Diabetes monitoring',
    'Failure-to-thrive care',
    'Chronic GI management',
    'Newborn examination',
    'Congenital anomaly screening',
    'Breastfeeding support',
    'Prematurity follow-up',
    'Puberty monitoring',
    'Adolescent menstrual care',
    'Sexual health counseling',
    'Mental health support',
    'Subspecialist coordination',
    'School communication',
    'Palliative care support',
    'Other'
  ],
  'Geriatrician': [
    'Comprehensive geriatric assessment',
    'Functional assessment',
    'Cognitive screening',
    'Chronic disease management',
    'Frailty management',
    'Medication review',
    'Deprescribing',
    'Dementia care',
    'Depression treatment',
    'Falls risk assessment',
    'Gait/balance evaluation',
    'Incontinence management',
    'Sleep disorder evaluation',
    'Palliative symptom control',
    'Multimorbidity care planning',
    'Advance care planning',
    'Outpatient geriatric clinic',
    'Inpatient geriatric consultation',
    'Long-term care visits',
    'Other'
  ],
  'Gynecologist': [
    'Well-woman exam',
    'Cervical cancer screening',
    'Breast exam',
    'HPV vaccination',
    'STI screening',
    'Menstrual disorder management',
    'Hormonal imbalance treatment',
    'Menopause management',
    'Preconception counseling',
    'Contraception provision',
    'Fertility evaluation',
    'Pelvic pain treatment',
    'Endometriosis management',
    'Fibroid monitoring',
    'Ovarian cyst care',
    'Vulvovaginal disorder treatment',
    'Urinary incontinence care',
    'Pelvic organ prolapse management',
    'Gynecologic cancer screening',
    'Colposcopy',
    'Biopsy/LEEP/cryotherapy',
    'Cancer surveillance',
    'Hysterectomy',
    'Myomectomy',
    'Salpingo-oophorectomy',
    'Endometrial ablation',
    'Hysteroscopic surgery',
    'Laparoscopic surgery',
    'Adolescent gynecology',
    'Sexual health counseling',
    'Sexual assault care',
    'Fertility preservation',
    'Other'
  ],
  'Obstetrician': [
    'Preconception counseling',
    'Chronic disease optimization',
    'Family planning advice',
    'Routine prenatal check-ups',
    'Obstetric ultrasound',
    'Prenatal screening',
    'High-risk pregnancy care',
    'Amniocentesis',
    'Chorionic villus sampling',
    'Cervical cerclage',
    'Labour/delivery management',
    'Induction of labour',
    'Operative vaginal delivery',
    'Cesarean section',
    'Labour complication management',
    'Obstetric emergency management',
    'Postpartum examination',
    'Postpartum complication management',
    'Postpartum depression screening',
    'Postnatal contraception',
    'Dilation and curettage',
    'Ectopic pregnancy management',
    'Cervical procedures',
    'Well-woman exam',
    'Menstrual disorder management',
    'Contraception provision',
    'Sterilization procedures',
    'Other'
  ],
  'Orthopedist': [
    'Musculoskeletal exam',
    'Imaging interpretation',
    'Pain management',
    'Physical therapy prescription',
    'Bracing/orthotics',
    'Joint injection',
    'Fracture care',
    'Surgical fixation',
    'Arthritis management',
    'Joint replacement',
    'Spine care',
    'Spine surgery',
    'Sports injury management',
    'Arthroscopic surgery',
    'Ligament reconstruction',
    'Hand surgery',
    'Foot/ankle surgery',
    'Pediatric orthopedics',
    'Tumor resection',
    'Pre/post-operative care',
    'Workers\' comp evaluation',
    'Other'
  ],
  'Ophthalmologist': [
    'Comprehensive eye exam',
    'Vision screening',
    'Refraction',
    'Corrective lens prescription',
    'Refractive error management',
    'Cataract diagnosis',
    'Glaucoma management',
    'Retinal disease treatment',
    'Corneal disease management',
    'Uveitis treatment',
    'Pediatric eye exam',
    'Amblyopia screening',
    'Strabismus management',
    'Cataract surgery',
    'LASIK/PRK',
    'Glaucoma surgery',
    'Corneal transplantation',
    'Retinal detachment repair',
    'Vitrectomy',
    'Strabismus surgery',
    'Eyelid surgery',
    'Orbital surgery',
    'Acute eye trauma care',
    'Corneal abrasion treatment',
    'Foreign body removal',
    'Acute glaucoma management',
    'Neuro-ophthalmology evaluation',
    'Low-vision assessment',
    'Low-vision aids prescription',
    'Other'
  ],
  'Otolaryngologist': [
    'Ear infection management',
    'Hearing loss evaluation',
    'Tinnitus management',
    'Vertigo treatment',
    'Ear wax removal',
    'Myringotomy',
    'Cholesteatoma surgery',
    'Cochlear implantation',
    'Sinusitis treatment',
    'Rhinitis management',
    'Nasal obstruction care',
    'Allergy evaluation',
    'Endoscopic sinus surgery',
    'Septoplasty',
    'Rhinoplasty',
    'Sore throat treatment',
    'Tonsillitis management',
    'Voice disorder treatment',
    'Dysphagia assessment',
    'Tonsillectomy',
    'Adenoidectomy',
    'LPR management',
    'Snoring evaluation',
    'Sleep apnea management',
    'Sleep study coordination',
    'Pediatric airway management',
    'Tracheotomy',
    'Head/neck cancer diagnosis',
    'Tumor resection',
    'Neck dissection',
    'Thyroidectomy',
    'Parotidectomy',
    'Reconstructive surgery',
    'Facial fracture management',
    'Facial plastic surgery',
    'Scar revision',
    'Pediatric ENT care',
    'Cleft lip/palate surgery',
    'Outpatient endoscopy',
    'Pre/postoperative care',
    'Other'
  ],
  'Dentist': [
    'Oral examination',
    'Oral cancer screening',
    'Dental radiography',
    'Teeth cleaning',
    'Fluoride application',
    'Dental sealants',
    'Fillings',
    'Inlays',
    'Onlays',
    'Root canal treatment',
    'Crowns',
    'Bridges',
    'Tooth extraction',
    'Impacted tooth removal',
    'Alveoloplasty',
    'Scaling',
    'Root planing',
    'Periodontal maintenance',
    'Gingivectomy',
    'Complete dentures',
    'Partial dentures',
    'Overdentures',
    'Implant crowns',
    'Implant bridges',
    'Implant overdentures',
    'Maxillofacial prosthesis',
    'Orthodontic diagnosis',
    'Removable appliances',
    'Space maintainers',
    'Clear aligners',
    'Teeth whitening',
    'Veneers',
    'Cosmetic bonding',
    'Pediatric preventive care',
    'Pulpotomy',
    'Stainless steel crowns',
    'Habit-breaking appliances',
    'Emergency pain management',
    'Abscess drainage',
    'Dental trauma management',
    'Repair of dental prostheses',
    'Other'
  ],
  'Periodontist': [
    'Periodontal assessment',
    'Non‑surgical therapy',
    'Scaling',
    'Root planning',
    'Root debridement',
    'Antimicrobial therapy',
    'Periodontal maintenance',
    'Flap surgery',
    'Pocket reduction',
    'Open debridement',
    'Regenerative procedures',
    'Tissue regeneration',
    'Bone grafting',
    'Gum grafting',
    'Soft tissue augmentation',
    'Frenectomy',
    'Gum contouring',
    'Crown lengthening',
    'Subgingival caries',
    'Implant evaluation',
    'Implant placement',
    'Socket grafting',
    'Ridge augmentation',
    'Sinus lift',
    'Implant soft tissue graft',
    'Peri‑implantitis management',
    'Mucosal diagnosis',
    'Gingival overgrowth',
    'Other'
  ],
  'Endodontist': [
    'Pulp vitality testing',
    'CBCT interpretation',
    'Root canal therapy',
    'Endodontic retreatment',
    'Apicoectomy',
    'Retrograde filling',
    'Periradicular surgery',
    'Pulpotomy',
    'Pulpectomy',
    'Direct pulp capping',
    'Indirect pulp capping',
    'Internal bleaching',
    'Trauma management',
    'Tooth replantation',
    'Splinting',
    'Cracked tooth management',
    'Internal resorption repair',
    'External resorption repair',
    'Abscess drainage',
    'Emergency pulpectomy',
    'Microscopic endodontics',
    'Ultrasonic instrumentation',
    'Obturation',
    'Rotary instrumentation',
    'Calcium hydroxide dressing',
    'Regenerative endodontics',
    'Apexification',
    'Apexogenesis',
    'Root canal sealing',
    'Post space preparation',
    'Surgical trephination',
    'Root amputation',
    'Hemisection',
    'Intentional replantation',
    'Other'
  ],
  'Prosthodontist': [
    'Inlays',
    'Onlays',
    'Crowns',
    'Veneers',
    'Fixed bridges',
    'Full mouth rehabilitation',
    'Complete dentures',
    'Partial dentures',
    'Implant overdentures',
    'Implant bridges',
    'Implant crowns',
    'Implant planning',
    'Bone grafting',
    'Sinus lift',
    'Abutment placement',
    'Cosmetic veneers',
    'Teeth whitening',
    'Occlusal analysis',
    'Occlusal splints',
    'Night guards',
    'TMJ therapy',
    'Trauma rehabilitation',
    'Maxillofacial prosthesis',
    'Obturator',
    'Cleft prosthesis',
    'Geriatric prosthodontics',
    'Special needs care',
    'Other'
  ],
  'Orthodontist': [
    'Orthodontic evaluation',
    'Diagnostic records',
    'Malocclusion diagnosis',
    'Early intervention',
    'Habit modification',
    'Myofunctional therapy',
    'Fixed appliances',
    'Metal braces',
    'Ceramic braces',
    'Clear aligners',
    'Removable appliances',
    'Palatal expansion',
    'Functional appliances',
    'Growth modification',
    'Temporary anchorage devices',
    'Retainer fitting',
    'Retention monitoring',
    'Multidisciplinary coordination',
    'Orthognathic planning',
    'Pre-surgical orthodontics',
    'Post-surgical orthodontics',
    'Other'
  ],
  'Sports Medicine Specialist': [
    'Injury evaluation',
    'Pre-participation exam',
    'Diagnostic imaging',
    'Concussion management',
    'Injection therapy',
    'Corticosteroid injection',
    'PRP injection',
    'Visco supplementation',
    'Arthroscopic surgery',
    'Ligament reconstruction',
    'Cartilage repair',
    'Fracture fixation',
    'Tendon repair',
    'Physical therapy',
    'Therapeutic exercise',
    'Functional rehabilitation',
    'Gait analysis',
    'Biomechanical screening',
    'Injury prevention',
    'Activity modification',
    'Bracing/taping',
    'Orthotic fitting',
    'Nutritional counseling',
    'Cardiac screening',
    'Female athlete triad management',
    'Return-to-play protocol',
    'Pain management',
    'Regenerative medicine',
    'Ultrasound guidance',
    'Neurocognitive testing',
    'Other'
  ],
  'Geneticist': [
    'Genetic counseling',
    'Prenatal diagnosis',
    'Carrier screening',
    'Newborn screening',
    'Dysmorphology exam',
    'Metabolic evaluation',
    'Chromosomal analysis',
    'Microarray analysis',
    'Exome sequencing',
    'Genome sequencing',
    'Variant interpretation',
    'Cancer risk assessment',
    'Family history',
    'Teratogen counseling',
    'Pharmacogenetic testing',
    'Reproductive risk',
    'Syndrome diagnosis',
    'Developmental assessment',
    'Biochemical testing',
    'Molecular diagnosis',
    'Prenatal testing (amniocentesis)',
    'Preconception counseling',
    'Cascade testing',
    'Surveillance planning',
    'Multidisciplinary coordination',
    'Inherited disease management',
    'Congenital anomaly evaluation',
    'Intellectual disability workup',
    'Connective tissue evaluation',
    'Cardiogenetic assessment',
    'Neurogenetic evaluation',
    'Mitochondrial disorder workup',
    'Skeletal dysplasia assessment',
    'Hereditary cancer panel',
    'Tumor germline testing',
    'Preimplantation guidance',
    'Recurrence risk counseling',
    'Diagnostic odyssey resolution',
    'Genomic board review',
    'Other'
  ],
  'Hepatologist': [
    'Liver evaluation',
    'Viral hepatitis',
    'Hepatitis B',
    'Hepatitis C',
    'Direct antiviral',
    'Autoimmune hepatitis',
    'Primary biliary cholangitis',
    'Primary sclerosing cholangitis',
    'Fatty liver',
    'NASH management',
    'Alcohol-related disease',
    'Wilson disease',
    'Hemochromatosis',
    'Alpha-1 antitrypsin',
    'Cirrhosis care',
    'Portal hypertension',
    'Ascites management',
    'Therapeutic paracentesis',
    'Variceal banding',
    'TIPS procedure',
    'Hepatic encephalopathy',
    'Lactulose therapy',
    'Liver cancer surveillance',
    'Hepatocellular carcinoma',
    'Tumor ablation',
    'TACE therapy',
    'Radioembolization (Y-90)',
    'Liver biopsy',
    'FibroScan elastography',
    'Fibrosis assessment',
    'Biliary disease',
    'Cholangitis treatment',
    'Gallbladder management',
    'ERCP coordination',
    'Liver transplant evaluation',
    'Transplant listing',
    'Post-transplant care',
    'Immunosuppression management',
    'Metabolic counseling',
    'Nutritional therapy',
    'Liver prevention',
    'Vaccination (hepatitis)',
    'Multidisciplinary coordination',
    'Other'
  ],
  'Sleep Specialist': [
    'Sleep history',
    'Physical exam',
    'Sleep diary',
    'Actigraphy',
    'Symptom questionnaire',
    'Polysomnography (PSG)',
    'Home sleep test',
    'CPAP titration',
    'BiPAP titration',
    'ASV titration',
    'Multiple sleep latency test (MSLT)',
    'Maintenance of wakefulness test (MWT)',
    'Overnight oximetry',
    'Insomnia diagnosis',
    'CBT-I therapy',
    'Sleep hygiene',
    'Stimulus control',
    'Sleep restriction',
    'Nightmare management',
    'Sleep apnea diagnosis',
    'Obstructive apnea',
    'Central apnea',
    'CPAP prescription',
    'PAP compliance monitoring',
    'Oral appliance referral',
    'Snoring evaluation',
    'Upper airway resistance',
    'Narcolepsy diagnosis',
    'Idiopathic hypersomnia',
    'Wake-promoting agents',
    'Circadian disorder',
    'Delayed sleep phase',
    'Advanced sleep phase',
    'Shift work disorder',
    'Jet lag treatment',
    'Light therapy',
    'Melatonin therapy',
    'Restless legs syndrome (RLS)',
    'Periodic limb movement disorder (PLMD)',
    'REM behavior disorder',
    'Night terrors',
    'Sleepwalking',
    'Sleep-related eating',
    'Nocturnal seizure evaluation',
    'Pediatric sleep apnea',
    'Pediatric insomnia',
    'Neurodevelopmental sleep issues',
    'Sleep-related hypertension',
    'Sleep-related arrhythmia',
    'Sleep-stroke risk',
    'Multidisciplinary coordination',
    'Other'
  ],
  'Urologist': [
    'UTI management',
    'LUTS treatment',
    'BPH management',
    'Hematuria evaluation',
    'Kidney stone management',
    'Stone surgery (ureteroscopy/ESWL/PCNL)',
    'Stone prevention counseling',
    'Incontinence management',
    'Urodynamic testing',
    'Non-surgical incontinence therapy',
    'Surgical incontinence procedures',
    'Urologic cancer management',
    'Prostate cancer screening',
    'Bladder cancer treatment',
    'Erectile dysfunction treatment',
    'Infertility treatment',
    'Peyronie\'s disease management',
    'Vasectomy/vasectomy reversal',
    'Pediatric UTI management',
    'Congenital abnormality treatment',
    'Circumcision',
    'BPH surgery (TURP/laser)',
    'Prostatectomy',
    'Urethral stricture management',
    'Urinary diversion creation',
    'Stoma care',
    'Genitourinary reconstruction',
    'Cystoscopy',
    'Ureteroscopy',
    'Ureteral stent placement',
    'Other'
  ],
  'General Practitioner': [
    'Initial assessment',
    'Physical examination',
    'Acute illness management',
    'Minor injury care',
    'Health check-up',
    'Lifestyle counseling',
    'Immunization administration',
    'Hypertension screening',
    'Diabetes screening',
    'Chronic disease management',
    'Medication prescription',
    'Follow-up visits',
    'Mental health screening',
    'Short-term counseling',
    'Antidepressant prescription',
    'Contraceptive counseling',
    'Basic antenatal care',
    'Gynecological problem management',
    'STI screening',
    'Breast cancer screening',
    'Cervical cancer screening',
    'Pediatric illness management',
    'Childhood immunization',
    'Growth monitoring',
    'School physical exam',
    'Diagnostic test ordering',
    'Specialist referral',
    'Post-hospital follow-up',
    'Health education',
    'Travel health advice',
    'Community outreach',
    'Other'
  ],
  'Pharmacist': [
    'Prescription dispensing',
    'Prescription review',
    'Interaction detection',
    'Medication therapy management',
    'Adverse reaction monitoring',
    'Dose adjustment',
    'Patient counseling',
    'Immunization delivery',
    'Health monitoring',
    'OTC advice',
    'Lifestyle education',
    'Sterile/non-sterile compounding',
    'Inventory management',
    'Technician supervision',
    'Record maintenance',
    'Clinical rounds',
    'Antimicrobial stewardship',
    'Drug information provision',
    'Other'
  ],
  'Immunologist': [
    'Allergy testing',
    'Immunodeficiency evaluation',
    'Pulmonary function testing',
    'Anaphylaxis challenge',
    'Drug challenge',
    'Food challenge',
    'Immunoglobulin replacement',
    'Biologic therapy',
    'Allergen immunotherapy',
    'Drug desensitization',
    'Chronic urticaria management',
    'Asthma management',
    'Atopic dermatitis care',
    'Sinusitis management',
    'Autoimmune disease treatment',
    'Vasculitis management',
    'Hereditary angioedema prophylaxis',
    'Immunoglobulin infusion',
    'SCIG therapy',
    'IVIg therapy',
    'Genetic testing',
    'Skin prick test',
    'Patch testing',
    'IgE testing',
    'Nasal smear',
    'Long-term monitoring',
    'Vaccine counseling',
    'Multidisciplinary clinic',
    'Pediatric immunology',
    'Neuroimmunology care',
    'Other'
  ],
  'Allergist': [
    'Allergy skin testing',
    'Blood IgE testing',
    'Pulmonary function testing',
    'Patch testing',
    'Drug challenge',
    'Food challenge',
    'Allergic rhinitis evaluation',
    'Asthma diagnosis',
    'Food allergy evaluation',
    'Drug allergy evaluation',
    'Insect sting evaluation',
    'Urticaria workup',
    'Atopic dermatitis evaluation',
    'Immunodeficiency workup',
    'Subcutaneous immunotherapy',
    'Sublingual immunotherapy',
    'Oral immunotherapy',
    'Drug desensitization',
    'Venom immunotherapy',
    'Asthma action plan',
    'Biologic therapy',
    'Chronic rhinosinusitis management',
    'Chronic urticaria management',
    'Eczema management',
    'Immunoglobulin replacement',
    'Avoidance counseling',
    'Anaphylaxis education',
    'Pediatric allergy care',
    'Adult allergy care',
    'Occupational allergy assessment',
    'Other'
  ],
  'Pathologist': [
    'Surgical pathology',
    'Cytopathology',
    'Autopsy pathology',
    'Histopathology',
    'Immunohistochemistry',
    'Electron microscopy',
    'Neuropathology',
    'Renal pathology',
    'Cardiac pathology',
    'Pulmonary pathology',
    'Gastrointestinal pathology',
    'Genitourinary pathology',
    'Gynecologic pathology',
    'Breast pathology',
    'Dermatopathology',
    'Endocrine pathology',
    'Head/neck pathology',
    'Soft tissue pathology',
    'Pediatric pathology',
    'Perinatal pathology',
    'Transplant pathology',
    'Ophthalmic pathology',
    'Clinical chemistry',
    'Hematology',
    'Coagulation',
    'Flow cytometry',
    'Urinalysis',
    'Bone marrow examination',
    'Microbiology',
    'Bacteriology',
    'Mycology',
    'Parasitology',
    'Mycobacteriology',
    'Virology',
    'Immunology',
    'Serology',
    'Blood banking',
    'Transfusion medicine',
    'HLA typing',
    'Apheresis',
    'Molecular diagnostics',
    'Genomic profiling',
    'Cytogenetics',
    'FISH analysis',
    'PCR testing',
    'Next-generation sequencing',
    'Precision diagnostics',
    'Toxicological analysis',
    'Therapeutic drug monitoring',
    'Point-of-care testing',
    'Phlebotomy',
    'Frozen section',
    'Fine needle aspiration',
    'Intraoperative consultation',
    'Tumor triage',
    'Second opinion',
    'Quality control',
    'Laboratory management',
    'Other'
  ],
  'Physiotherapist / Physical Therapist': [
    'Physical evaluation',
    'Treatment planning',
    'Manual therapy',
    'Therapeutic modalities',
    'Pain management',
    'Post-operative rehab',
    'Orthopedic rehab',
    'Sports injury rehab',
    'Stroke rehabilitation',
    'Neurological rehab',
    'Vestibular rehab',
    'Balance training',
    'Gait training',
    'Transfer training',
    'Cardiac rehab',
    'Pulmonary rehab',
    'Fall prevention',
    'Assistive device training',
    'Prosthetic training',
    'Orthotic prescription',
    'Therapeutic exercise',
    'Strengthening',
    'Stretching',
    'Endurance training',
    'Proprioceptive training',
    'Core stabilization',
    'Pediatric rehab',
    'Pelvic floor therapy',
    'Prenatal/postnatal rehab',
    'Lymphedema management',
    'Hand therapy',
    'Wound care',
    'Other'
  ],
  'Nursing': [
    'Vital Signs Monitoring',
    'Wound Dressing',
    'Injection Administration',
    'Home Health Visit',
    'Health Screening',
    'Patient Triage',
    'Other'
  ],
  'Forensic Pathologist': [
    'Autopsy performance',
    'Cause of death determination',
    'Time of death estimation',
    'Injury pattern analysis',
    'Crime scene investigation',
    'Evidence collection',
    'Toxicology interpretation',
    'Medical record review',
    'Expert legal testimony',
    'Post-mortem examination',
    'Identification of unknown remains',
    'Skeletal remains analysis',
    'Child fatality review',
    'Histopathological examination',
    'Forensic imaging (X-ray/CT)',
    'Biological specimen collection',
    'DNA sample handling',
    'Trace evidence preservation',
    'Death certificate completion',
    'Multidisciplinary coordination',
    'Other'
  ],
  'Diabetologist': [
    'Diabetes diagnosis/classification',
    'Type 1 diabetes management',
    'Type 2 diabetes management',
    'Gestational diabetes care',
    'Glycemic goal setting',
    'Individualized nutrition plan',
    'Insulin therapy initiation',
    'Insulin pump management',
    'CGM (Continuous Glucose Monitoring)',
    'Blood glucose interpretation',
    'HbA1c monitoring',
    'Hypoglycemia management',
    'DKA/HHS prevention',
    'Diabetic foot screening',
    'Neuropathy assessment',
    'Retinopathy screening coordination',
    'Nephropathy monitoring',
    'Cardiovascular risk control',
    'Lifestyle/exercise counseling',
    'Medication management',
    'Diabetes education/self-care',
    'Weight management support',
    'Other'
  ],
  'Pain Management Specialist': [
    'Chronic pain evaluation',
    'Acute pain management',
    'Comprehensive history/exam',
    'Diagnostic blocks',
    'Epidural steroid injections',
    'Facet joint injections',
    'Nerve root blocks',
    'Sacroiliac joint injections',
    'Trigger point injections',
    'Radiofrequency ablation',
    'Spinal cord stimulation trials',
    'Intrathecal pump management',
    'Joint/bursa injections',
    'Sympathetic nerve blocks',
    'Neuropathic pain management',
    'Fibromyalgia treatment',
    'Cancer pain management',
    'Medication management',
    'Physical therapy coordination',
    'Psychological pain support',
    'Interventional pain procedures',
    'Regenerative medicine (PRP)',
    'Other'
  ],
  'Tropical Disease Specialist': [
    'Malaria diagnosis/treatment',
    'Dengue fever management',
    'Typhoid/enteric fever care',
    'Leishmaniasis treatment',
    'Schistosomiasis management',
    'Trypanosomiasis treatment',
    'Cholera/waterborne disease care',
    'Leprosy management',
    'Tuberculosis coordination',
    'Parasitic infection screening',
    'Helminthic disease treatment',
    'Viral hemorrhagic fever care',
    'Rickettsial disease treatment',
    'Emerging infectious diseases',
    'Zoonotic disease management',
    'Travel medicine counseling',
    'Pre-travel vaccination',
    'Post-travel evaluation',
    'Outbreak investigation',
    'Public health advocacy',
    'Other'
  ],
  'Maternity Care': [
    'Antenatal check-up',
    'Fetal heart monitoring',
    'Fundal height measurement',
    'Routine prenatal screening',
    'Maternal health assessment',
    'Nutritional counseling (pregnancy)',
    'Birth planning facilitation',
    'Labor support/monitoring',
    'Postnatal physical exam',
    'Postpartum hemorrhage monitor',
    'Newborn assessment (initial)',
    'Breastfeeding support/LATC',
    'Infant feeding education',
    'Wound care (episiotomy/CS)',
    'Postnatal depression screening',
    'Family planning counseling',
    'Contraceptive provision',
    'Immunization (mother/infant)',
    'Parenting education',
    'Mental health support',
    'Pelvic floor health advice',
    'Other'
  ],
  'Medical Radiation Scientist / Radiographer (Diagnostic Imaging)': [
    'Patient positioning',
    'Radioactive source handling',
    'Image acquisition/processing',
    'Technique optimization',
    'Radiation safety/shielding',
    'Quality control testing',
    'Electronic archiving',
    'Anatomy/pathology recognition',
    'Safety protocol adherence',
    'Clinician collaboration',
    'Equipment maintenance',
    'Patient record upkeep',
    'Contrast media administration',
    'Emergency response',
    'Staff training participation',
    'Other'
  ],
  'Radiographer / Medical Imaging Technologist': [
    'Patient identification/prep',
    'X-ray acquisition',
    'CT scan performance',
    'MRI scanning',
    'Ultrasound support',
    'Image quality evaluation',
    'Equipment calibration',
    'Radiation dosage monitoring',
    'Digital imaging storage',
    'Sterile technique application',
    'Vital sign monitoring (sedated)',
    'Standard procedure adherence',
    'Clinician collaboration',
    'Patient care/instruction',
    'Quality improvement',
    'Other'
  ],
  'Pulmonologist': [
    'Respiratory risk assessment',
    'Pre-operative evaluation',
    'Smoking cessation counseling',
    'Inhaler technique education',
    'Respiratory history',
    'Physical examination',
    'Occupational exposure assessment',
    'Pulmonary function tests',
    'Blood gas analysis',
    'Pulse oximetry',
    'Sputum evaluation',
    'Allergy testing',
    'Chest X-ray interpretation',
    'CT interpretation',
    'PET-CT interpretation',
    'Polysomnography',
    'Asthma management',
    'COPD management',
    'Interstitial lung disease management',
    'Bronchiectasis management',
    'Tuberculosis management',
    'Pulmonary hypertension management',
    'Pulmonary embolism follow-up',
    'Lung cancer evaluation',
    'Sleep apnea management',
    'Cystic fibrosis care',
    'Long-COVID care',
    'Bronchoscopy',
    'Transbronchial biopsy',
    'Thoracentesis',
    'Image-guided lung biopsy',
    'Chest tube placement',
    'Respiratory infection management',
    'Long-term oxygen therapy',
    'Inhaler optimization',
    'Mucolytic therapy',
    'Pulmonary rehabilitation',
    'Acute respiratory failure management',
    'Mechanical ventilation',
    'Tracheostomy care',
    'Other'
  ],
  'Gastroenterologist': [
    'GI consultation',
    'Dyspepsia evaluation',
    'GERD assessment',
    'Abdominal pain evaluation',
    'Bowel habit assessment',
    'Rectal bleeding evaluation',
    'Dysphagia assessment',
    'Jaundice workup',
    'Nutritional counseling',
    'Pre-endoscopy assessment',
    'History/physical exam',
    'Lab test interpretation',
    'Imaging guidance',
    'Ambulatory monitoring',
    'EGD',
    'Colonoscopy',
    'Sigmoidoscopy',
    'Enteroscopy',
    'Capsule endoscopy',
    'Polypectomy',
    'Foreign body retrieval',
    'Bleeding control',
    'Variceal banding',
    'ERCP',
    'Endoscopic ultrasound',
    'Fine-needle aspiration',
    'Stricture dilation',
    'PEG placement',
    'Esophageal disorder management',
    'Gastric disorder management',
    'Peptic ulcer treatment',
    'H. pylori eradication',
    'IBS management',
    'IBD management',
    'Celiac disease management',
    'SIBO management',
    'Diverticular disease management',
    'Colorectal cancer surveillance',
    'Pancreatitis management',
    'Gallstone management',
    'Biliary obstruction management',
    'Hepatitis management',
    'Fatty liver management',
    'Cirrhosis management',
    'Portal hypertension management',
    'Malabsorption management',
    'Functional GI disorder treatment',
    'Nutrition support coordination',
    'Acute GI bleeding management',
    'Severe IBD flare management',
    'Acute cholangitis management',
    'High-risk surveillance',
    'Surgical coordination',
    'Other'
  ],
  'Nephrologist': [
    'CKD staging',
    'BP management',
    'Diabetes management',
    'Kidney health education',
    'History/physical exam',
    'Blood test interpretation',
    'Urine test interpretation',
    'Kidney ultrasound',
    'Kidney biopsy',
    'Acute kidney injury management',
    'Chronic kidney disease follow-up',
    'Glomerulonephritis management',
    'Nephrotic syndrome management',
    'Electrolyte disorder treatment',
    'Acid-base disorder treatment',
    'Secondary hypertension evaluation',
    'Kidney stone evaluation',
    'Complicated UTI management',
    'Hemodialysis prescription',
    'Peritoneal dialysis prescription',
    'Vascular access management',
    'Pre-transplant evaluation',
    'Post-transplant management',
    'Onconephrology care',
    'Critical care nephrology',
    'Other'
  ],
  'Endocrinologist': [
    'Endocrine history/exam',
    'Lifestyle counseling',
    'Pre-operative assessment',
    'Endocrine testing',
    'Dynamic tests',
    'DXA interpretation',
    'Imaging interpretation',
    'Diabetes management',
    'Gestational diabetes care',
    'Complication management',
    'Obesity management',
    'Thyroid disorder management',
    'Thyroid nodule management',
    'Thyroid cancer follow-up',
    'Parathyroid disorder management',
    'Pituitary disorder management',
    'Adrenal disorder management',
    'PCOS management',
    'Hypogonadism management',
    'Puberty disorder management',
    'Menopause management',
    'Growth disorder management',
    'Osteoporosis treatment',
    'Metabolic bone disease management',
    'Vitamin D management',
    'Endocrine tumor management',
    'Multidisciplinary coordination',
    'Hormonal emergency management',
    'Hormone replacement monitoring',
    'Diabetes technology management',
    'Primary care coordination',
    'Other'
  ],
  'Oncologist': [
    'Cancer diagnosis',
    'Cancer staging',
    'Risk assessment',
    'Molecular testing',
    'Tumor biopsy',
    'Bone marrow biopsy',
    'Treatment planning',
    'Chemotherapy',
    'Immunotherapy',
    'Targeted therapy',
    'Hormonal therapy',
    'Radiation therapy',
    'Surgical oncology',
    'Palliative care',
    'Pain management',
    'Symptom management',
    'Side effect management',
    'Supportive care',
    'Survivorship care',
    'Follow-up care',
    'Second opinion',
    'Clinical trials',
    'Multidisciplinary coordination',
    'Patient education',
    'Genetic counseling',
    'Fertility preservation',
    'End-of-life care',
    'Other'
  ],
  'Hematologist': [
    'Hematology consultation',
    'Blood count evaluation',
    'Bleeding workup',
    'Thrombosis risk assessment',
    'CBC interpretation',
    'Peripheral smear review',
    'Coagulation testing',
    'Bone marrow biopsy',
    'Anemia management',
    'Hemophilia care',
    'DVT/PE management',
    'Sickle cell care',
    'Thalassemia management',
    'Leukemia treatment',
    'Lymphoma treatment',
    'Myeloma treatment',
    'MDS management',
    'Myeloproliferative neoplasm care',
    'Chemotherapy administration',
    'Targeted therapy',
    'Immunotherapy',
    'Blood transfusion',
    'Platelet transfusion',
    'Factor replacement',
    'IV iron infusion',
    'Therapeutic phlebotomy',
    'Plasmapheresis',
    'Stem cell transplant coordination',
    'Chronic disease follow-up',
    'Multidisciplinary coordination',
    'Patient education',
    'Other'
  ],
  'Rheumatologist': [
    'Musculoskeletal history/exam',
    'Joint pain evaluation',
    'Osteoporosis counseling',
    'Autoimmune risk counseling',
    'Lab test interpretation',
    'Imaging interpretation',
    'Arthrocentesis',
    'Synovial fluid analysis',
    'Rheumatoid arthritis management',
    'Psoriatic arthritis management',
    'Ankylosing spondylitis care',
    'Lupus management',
    'Scleroderma care',
    'Vasculitis management',
    'Gout treatment',
    'Pseudogout management',
    'Osteoarthritis care',
    'Fibromyalgia management',
    'Tendonitis/bursitis treatment',
    'Osteoporosis diagnosis',
    'Bone density testing',
    'Bisphosphonate therapy',
    'DMARD prescription',
    'Biologic therapy',
    'Corticosteroid therapy',
    'Intra-articular injection',
    'Soft-tissue injection',
    'Long-term monitoring',
    'Multidisciplinary coordination',
    'Patient self-management education',
    'Other'
  ],
  'Radiologist': [
    'X-ray',
    'Dental imaging',
    'CT imaging',
    'MRI',
    'Ultrasound',
    'Fluoroscopy',
    'Mammography',
    'Nuclear medicine',
    'PET/CT',
    'Angiography',
    'Breast cancer screening',
    'Lung cancer screening',
    'Cardiovascular screening',
    'CT colonography',
    'Bone densitometry',
    'Image-guided biopsy',
    'Drainage procedures',
    'Vascular interventions',
    'Tumor ablation',
    'Central venous access',
    'GI/GU interventions',
    'Pain management procedures',
    'Neuroradiology',
    'Musculoskeletal radiology',
    'Cardiovascular radiology',
    'Breast imaging',
    'Pediatric radiology',
    'Emergency radiology',
    'Body imaging',
    'Radiation risk consultation',
    'Radiotherapy planning',
    'Quality/safety oversight',
    'Other'
  ],
  'Anesthesiologist': [
    'Perioperative evaluation',
    'Anesthesia planning',
    'General anesthesia',
    'Regional anesthesia',
    'Neuraxial blockade',
    'Spinal anesthesia',
    'Epidural anesthesia',
    'Combined spinal-epidural',
    'Local anesthesia',
    'Monitored anesthesia care',
    'Intravenous sedation',
    'Peripheral nerve block',
    'Ultrasound guidance',
    'Airway management',
    'Endotracheal intubation',
    'Laryngeal mask airway',
    'Mechanical ventilation',
    'Vital signs monitoring',
    'Hemodynamic monitoring',
    'Transesophageal echocardiography',
    'Point-of-care ultrasound',
    'Fluid management',
    'Blood transfusion',
    'Patient positioning',
    'Intraoperative life support',
    'Post-anesthesia recovery',
    'Postoperative pain management',
    'Patient-controlled analgesia',
    'Epidural analgesia',
    'Nerve block infusion',
    'Multimodal analgesia',
    'Acute pain service',
    'Chronic pain management',
    'Interventional pain procedures',
    'Epidural steroid injection',
    'Facet joint injection',
    'Nerve root block',
    'Sympathetic block',
    'Trigger point injection',
    'Joint injection',
    'Bursa injection',
    'Tendon sheath injection',
    'Radiofrequency ablation',
    'Spinal cord stimulation',
    'Intrathecal pump implantation',
    'Ketamine infusion',
    'Lidocaine infusion',
    'Palliative pain care',
    'Obstetric anesthesia',
    'Labor epidural',
    'Cesarean section anesthesia',
    'High-risk pregnancy anesthesia',
    'Cardiac anesthesia',
    'Cardiopulmonary bypass',
    'Thoracic anesthesia',
    'Vascular anesthesia',
    'Neuroanesthesia',
    'Awake craniotomy',
    'Intraoperative neuromonitoring',
    'Orthopedic anesthesia',
    'Regional block for joint surgery',
    'Pediatric anesthesia',
    'Neonatal anesthesia',
    'Infant sedation',
    'Ambulatory anesthesia',
    'Outpatient sedation',
    'Trauma anesthesia',
    'Emergency anesthesia',
    'Resuscitation',
    'Advanced cardiac life support',
    'Critical care medicine',
    'Intensive care unit management',
    'Postoperative ICU care',
    'Mechanical ventilation management',
    'Hemodynamic support',
    'Multisystem organ failure',
    'Transplant anesthesia',
    'Solid organ transplant',
    'Bariatric anesthesia',
    'Oncologic anesthesia',
    'Urologic anesthesia',
    'Gynecologic anesthesia',
    'Ophthalmic anesthesia',
    'Otolaryngology anesthesia',
    'Dental anesthesia',
    'Procedural sedation',
    'Endoscopy sedation',
    'Bronchoscopy sedation',
    'Radiology sedation',
    'MRI sedation',
    'CT sedation',
    'Cath lab sedation',
    'Electroconvulsive therapy anesthesia',
    'Burn anesthesia',
    'Geriatric anesthesia',
    'Obstructive sleep apnea management',
    'Difficult airway management',
    'Emergence delirium management',
    'Postoperative nausea prevention',
    'Perioperative temperature management',
    'Perioperative coagulation management',
    'Perioperative glycemic control',
    'Goal-directed fluid therapy',
    'Blood conservation',
    'Cell salvage',
    'Acute normovolemic hemodilution',
    'Prehabilitation consultation',
    'Multidisciplinary team coordination',
    'Quality assurance',
    'Perioperative protocol development',
    'Clinical research',
    'Resident education',
    'Medical student teaching',
    'Simulation training',
    'Patient safety initiatives',
    'Other'
  ],
  'Surgeon': [
    'Appendectomy',
    'Cholecystectomy',
    'Herniorrhaphy',
    'Colectomy',
    'Gastrectomy',
    'Bowel resection',
    'Laparotomy',
    'Laparoscopy',
    'Endoscopy',
    'Colonoscopy',
    'Gastroscopy',
    'EGD',
    'Polypectomy',
    'Hemorrhoidectomy',
    'Fistulectomy',
    'Abscess drainage',
    'Debridement',
    'Mastectomy',
    'Lumpectomy',
    'Breast biopsy',
    'Thyroidectomy',
    'Parathyroidectomy',
    'Adrenalectomy',
    'Splenectomy',
    'Pancreatectomy',
    'Liver resection',
    'Nephrectomy',
    'Cystectomy',
    'Prostatectomy',
    'Hysterectomy',
    'Oophorectomy',
    'Vasectomy',
    'Orchiectomy',
    'Penectomy',
    'Skin grafting',
    'Excision of cyst',
    'Excision of lipoma',
    'Tumor resection',
    'Tracheostomy',
    'Thoracotomy',
    'Craniotomy',
    'Laminectomy',
    'Fracture fixation',
    'Amputation',
    'Fasciotomy',
    'Suture',
    'Burns debridement',
    'Pilonidal sinus excision',
    'Pyloromyotomy',
    'Fundoplication',
    'Bariatric surgery',
    'Vagotomy',
    'Other'
  ],
  'Plastic Surgeon': [
    'Grafting',
    'Flapping',
    'Scarring',
    'Mastopexy',
    'Reduction',
    'Augmentation',
    'Rhinoplasty',
    'Blepharoplasty',
    'Otoplasty',
    'Abdominoplasty',
    'Liposuction',
    'Browlift',
    'Facelift',
    'Cheiloplasty',
    'Palatoplasty',
    'Cranioplasty',
    'Microtia',
    'Syndactyly',
    'Hypospadias',
    'Microsurgery',
    'Replantation',
    'Expansion',
    'Botox',
    'Filler',
    'Peel',
    'Laser',
    'Hairtransplant',
    'Vaginoplasty',
    'Labiaplasty',
    'Phalloplasty',
    'Gynecomastia',
    'Handsurgery',
    'Nerve',
    'Tendon',
    'Vascular',
    'Flap',
    'Implant',
    'Salvage',
    'Burn',
    'Wound',
    'Fracture',
    'Cleft',
    'Craniofacial',
    'Limb',
    'Breast',
    'Head',
    'Neck',
    'Scar',
    'Tattoo',
    'Vein',
    'Lip',
    'Chin',
    'Jaw',
    'Ear',
    'Nose',
    'Eyelid',
    'Forehead',
    'Arm',
    'Thigh',
    'Buttock',
    'Abdomen',
    'Back',
    'Chest',
    'Genital',
    'Penile',
    'Circumcision',
    'Tenolysis',
    'Neurolysis',
    'Arthrolysis',
    'Osteotomy',
    'Bone',
    'Cartilage',
    'Skin',
    'Fat',
    'Muscle',
    'Fascia',
    'Periosteum',
    'Mucosa',
    'Scalp',
    'Trunk',
    'Extremity',
    'Digit',
    'Toe',
    'Finger',
    'Wrist',
    'Elbow',
    'Shoulder',
    'Hip',
    'Knee',
    'Ankle',
    'Foot',
    'Hand',
    'Face',
    'Thorax',
    'Pelvis',
    'Perineum',
    'Other'
  ],
  'Bariatric Surgeon': [
    'Bariatric consultation',
    'Obesity evaluation',
    'BMI assessment',
    'Comorbidity screening',
    'Preoperative workup',
    'Nutrition counseling',
    'Psychological clearance',
    'Sleeve gastrectomy',
    'Gastric bypass',
    'Gastric banding',
    'BPD/DS',
    'SADI-S',
    'Intragastric balloon',
    'Revisional surgery',
    'Laparoscopic surgery',
    'Robotic surgery',
    'Postoperative monitoring',
    'Complication management',
    'Nutritional support',
    'Metabolic management',
    'Diabetes remission',
    'Hypertension control',
    'Lipid management',
    'Sleep apnea care',
    'Weight maintenance',
    'Support group referral',
    'Body contouring referral',
    'Long-term follow-up',
    'Other'
  ],
  'Vascular Surgeon': [
    'Vascular assessment',
    'Medical management',
    'Lifestyle counseling',
    'Risk factor management',
    'Ultrasound imaging',
    'ABI testing',
    'CTA interpretation',
    'MRA interpretation',
    'Angiography',
    'Claudication care',
    'Diabetic foot care',
    'Limb salvage',
    'Wound care',
    'Amputation prevention',
    'Carotid endarterectomy',
    'Carotid stenting',
    'TCAR',
    'Aneurysm repair',
    'EVAR',
    'TEVAR',
    'Open aneurysm repair',
    'Aortic dissection repair',
    'Peripheral bypass',
    'Femoropopliteal bypass',
    'Femorodistal bypass',
    'Aortobifemoral bypass',
    'Angioplasty',
    'Stent placement',
    'Atherectomy',
    'Thrombolytic therapy',
    'Embolectomy',
    'Thrombectomy',
    'Varicose vein treatment',
    'Endovenous ablation',
    'Sclerotherapy',
    'Phlebectomy',
    'Venous stenting',
    'IVC filter placement',
    'Dialysis access',
    'AV fistula creation',
    'AV graft placement',
    'Dialysis catheter management',
    'Peritoneal dialysis access',
    'Access thrombectomy',
    'Mesenteric ischemia repair',
    'Renal artery stenting',
    'Thoracic outlet decompression',
    'Popliteal entrapment release',
    'Lymphedema care',
    'Lymphatic surgery',
    'Trauma repair',
    'Vascular graft placement',
    'Hybrid procedure',
    'Second opinion',
    'Reconstructive surgery',
    'Amputation',
    'Postoperative care',
    'Long-term surveillance',
    'Other'
  ],
  'Colorectal Surgeon': [
    'Colonoscopy',
    'Sigmoidoscopy',
    'Polypectomy',
    'EMR',
    'ESD',
    'Anoscopy',
    'Proctoscopy',
    'Endorectal ultrasound',
    'Anorectal manometry',
    'Defecography',
    'Hemorrhoidectomy',
    'Hemorrhoidopexy',
    'Anal fissure surgery',
    'Lateral sphincterotomy',
    'Anal fistula surgery',
    'Fistulotomy',
    'Seton placement',
    'LIFT procedure',
    'Abscess drainage',
    'Colectomy',
    'Right colectomy',
    'Left colectomy',
    'Sigmoid colectomy',
    'Anterior resection',
    'Low anterior resection',
    'Abdominoperineal resection',
    'Total proctocolectomy',
    'Ileal pouch',
    'IPAA',
    'Total mesorectal excision',
    'taTME',
    'Laparoscopic surgery',
    'Robotic surgery',
    'Diverticulitis resection',
    'Hartmann procedure',
    'Crohn resection',
    'Strictureplasty',
    'Fistula repair',
    'Ulcerative colitis surgery',
    'Familial polyposis',
    'Lynch syndrome',
    'Polyposis management',
    'Fecal incontinence surgery',
    'Sphincteroplasty',
    'Sacral nerve stimulation',
    'Rectopexy',
    'Ventral rectopexy',
    'Perineal rectosigmoidectomy',
    'STARR procedure',
    'Colostomy creation',
    'Ileostomy creation',
    'Stoma reversal',
    'Volvulus surgery',
    'Toxic megacolon surgery',
    'Ischemic colitis resection',
    'Perforated colon repair',
    'Cancer staging',
    'Multidisciplinary coordination',
    'Postoperative care',
    'Stoma care',
    'Wound management',
    'Nutritional support',
    'Pelvic floor rehabilitation',
    'Second opinion',
    'Surveillance program',
    'Other'
  ],
  'Cardiothoracic Surgeon': [
    'CABG',
    'Valvectomy',
    'Valvuloplasty',
    'Thoracotomy',
    'Lobectomy',
    'Pneumonectomy',
    'Esophagectomy',
    'Septectomy',
    'Transplantation',
    'Thoracoscopy',
    'Other'
  ],
  'Neurosurgeon': [
    'Craniotomy',
    'Tumor resection',
    'Aneurysm clipping',
    'Endovascular coiling',
    'Decompressive craniectomy',
    'Shunt placement',
    'Endoscopic third ventriculostomy',
    'Spinal fusion',
    'Microdiscectomy',
    'Laminectomy',
    'Spinal cord decompression',
    'Deep brain stimulation',
    'Peripheral nerve release',
    'Epilepsy surgery',
    'Skull base surgery',
    'Stereotactic radiosurgery',
    'Other'
  ],
  'Pediatric Surgeon': [
    'Prenatal counseling',
    'Neonatal surgery',
    'Esophageal atresia repair',
    'Congenital diaphragmatic hernia repair',
    'Abdominal wall defect repair',
    'Intestinal atresia repair',
    'Hirschsprung surgery',
    'Appendectomy',
    'Hernia repair (inguinal/umbilical)',
    'Circumcision',
    'Cholecystectomy',
    'Splenectomy',
    'G-tube placement',
    'Orchiopexy',
    'Testicular torsion surgery',
    'Trauma laparotomy',
    'Burn management',
    'Tumor resection (neuroblastoma/Wilms)',
    'Lymph node biopsy',
    'Pediatric liver transplant',
    'Pediatric kidney transplant',
    'Portal shunt surgery',
    'Endoscopy (EGD/colonoscopy)',
    'Laparoscopic surgery',
    'Thoracoscopic surgery',
    'Fundoplication',
    'Pyloromyotomy',
    'Ostomy creation/reversal',
    'Chest wall repair',
    'Soft tissue excision',
    'Vascular malformation surgery',
    'Muscle biopsy',
    'Other'
  ],
  'Oral & Maxillofacial Surgeon': [
    'Tooth extraction',
    'Wisdom tooth removal',
    'Dental implant placement',
    'Bone grafting',
    'Ridge augmentation',
    'Sinus lift',
    'Mandibular fracture repair',
    'Maxillary fracture repair',
    'Orbital fracture repair',
    'Zygomatic fracture repair',
    'Nasal fracture reduction',
    'Soft tissue laceration repair',
    'Orthognathic surgery',
    'Jaw realignment',
    'Distraction osteogenesis',
    'Cleft lip repair',
    'Cleft palate repair',
    'Craniofacial surgery',
    'TMJ arthroscopy',
    'TMJ arthrocentesis',
    'TMJ replacement',
    'Oral biopsy',
    'Tumor resection',
    'Neck dissection',
    'Other'
  ],
  'Dietitian / Nutritionist': [
    'Nutritional status assessment',
    'Dietary history evaluation',
    'Malnutrition risk identification',
    'Medical nutrition therapy',
    'Nutrient requirement prescription',
    'Therapeutic diet planning',
    'Enteral/parenteral nutrition',
    'Nutrition support rounds',
    'Clinical progress monitoring',
    'Dietary counseling',
    'Group nutrition education',
    'Medical record documentation',
    'Therapeutic menu advising',
    'Preventive nutrition promotion',
    'Evidence-based guideline update',
    'Quality improvement participation',
    'Other'
  ],
  'Optometrist': [
    'Comprehensive eye exam',
    'Vision disorder diagnosis',
    'Eye disease detection',
    'Systemic condition identification',
    'Corrective lens prescription',
    'Low-vision aid prescription',
    'Vision therapy',
    'Ophthalmic medication management',
    'Minor ocular procedures',
    'Common eye condition management',
    'Eye health counseling',
    'Occupational/sports vision advice',
    'Specialist referral coordination',
    'Patient record documentation',
    'Post-operative vision follow-up',
    'Contact lens care guidance',
    'Other'
  ],
  'Occupational Therapist': [
    'Functional assessment',
    'Goal setting',
    'ADL training',
    'Adaptive equipment training',
    'Home safety evaluation',
    'Environmental modification',
    'Assistive device prescription',
    'Workstation ergonomics',
    'Job coaching',
    'Return-to-work planning',
    'School-based intervention',
    'Hand therapy',
    'Splinting',
    'Edema management',
    'Scar mobilization',
    'Fine motor training',
    'Sensory re-education',
    'Constraint-induced therapy',
    'Cognitive rehabilitation',
    'Memory training',
    'Executive function training',
    'Pediatric developmental therapy',
    'Sensory integration',
    'Play-based intervention',
    'Handwriting training',
    'Mental health intervention',
    'Activity scheduling',
    'Social skills training',
    'Lifestyle redesign',
    'Discharge planning',
    'Caregiver education',
    'Fall prevention',
    'Community reintegration',
    'Other'
  ],
  'Speech and Language Therapist (Speech‑Language Pathologist)': [
    'Speech evaluation',
    'Language assessment',
    'Articulation therapy',
    'Phonological treatment',
    'Receptive language therapy',
    'Expressive language therapy',
    'Pragmatic skills training',
    'Social communication',
    'Literacy support',
    'Apraxia therapy',
    'Dysarthria treatment',
    'Fluency therapy',
    'Stuttering intervention',
    'Voice therapy',
    'Vocal hygiene counseling',
    'Post‑laryngectomy rehab',
    'Cognitive‑communication therapy',
    'Memory training',
    'Executive function training',
    'Dysphagia assessment',
    'Swallow therapy',
    'Feeding therapy',
    'Oral‑motor therapy',
    'AAC assessment',
    'AAC training',
    'Parent coaching',
    'Caregiver education',
    'Early intervention',
    'School‑based therapy',
    'Telepractice',
    'Other'
  ],
  'Athletic Trainer / Sports Therapist': [
    'Injury evaluation and diagnosis',
    'Emergency first aid',
    'Injury prevention programs',
    'Individualized rehab programs',
    'Therapeutic modality application',
    'Recovery progress monitoring',
    'Return-to-play readiness',
    'Injury prevention education',
    'Medical record keeping',
    'Interprofessional collaboration',
    'Safety regulation compliance',
    'Athlete wellness promotion',
    'Pre-participation screening',
    'Concussion protocol management',
    'Psychological injury support',
    'Team event coverage',
    'Other'
  ],
  'Audiologist': [
    'Hearing evaluation',
    'Audiometric testing',
    'Hearing loss classification',
    'Vestibular assessment',
    'Hearing aid fitting',
    'Cochlear implant management',
    'Aural rehabilitation',
    'Tinnitus management',
    'Auditory processing assessment',
    'Cerumen removal',
    'Hearing conservation',
    'Hearing health education',
    'Medical referral',
    'Interprofessional collaboration',
    'Longitudinal monitoring',
    'Quality improvement',
    'Other'
  ],
  'Art Therapist': [
    'Psycho-emotional assessment',
    'Art therapy planning',
    'Art-based intervention',
    'Creative self-expression',
    'Coping support',
    'Therapeutic communication',
    'Progress documentation',
    'Group/individual sessions',
    'Art psychoeducation',
    'Multidisciplinary collaboration',
    'Adaptive intervention',
    'Mastery promotion',
    'Grief/trauma support',
    'Ethical boundaries',
    'Psychosocial advocacy',
    'Staff art therapy training',
    'Other'
  ],
  'Biomedical Scientist / Medical Laboratory Scientist': [
    'Specimen processing',
    'Laboratory test performance',
    'Hematology analysis',
    'Pathogen identification',
    'Body fluid chemistry',
    'Blood compatibility testing',
    'Instrument operation/calibration',
    'Quality control monitoring',
    'Result validation/interpretation',
    'Result reporting',
    'Critical value notification',
    'Documentation maintenance',
    'Biosafety adherence',
    'Accreditation participation',
    'Pathologist collaboration',
    'Test development/research',
    'Serial disease monitoring',
    'Other'
  ],
  'Cardiovascular Technologist / Cardiac Sonographer': [
    'Cardiac ultrasound imaging',
    'Doppler flow measurement',
    'Peripheral vascular ultrasound',
    'Invasive procedure assistance',
    'Vital signs monitoring',
    'ECG stress testing',
    'Patient preparation/consent',
    'Abnormal waveform recognition',
    'Sterile field maintenance',
    'Equipment calibration/maintenance',
    'Digital image archiving',
    'Preliminary measurement summary',
    'Multidisciplinary collaboration',
    'Infection/radiation safety',
    'Quality assurance participation',
    'Student supervision/training',
    'Other'
  ],
  'Chiropractor': [
    'Patient history/exam',
    'Neuromusculoskeletal diagnosis',
    'Spinal joint manipulation',
    'Soft-tissue techniques',
    'Therapeutic modalities',
    'Therapeutic exercise prescription',
    'Posture/ergonomics advice',
    'Lifestyle wellness counseling',
    'Progress reassessment',
    'Red-flag referral',
    'Clinical record keeping',
    'Multidisciplinary collaboration',
    'Self-care education',
    'Community health promotion',
    'Scope compliance',
    'Other'
  ],
  'Clinical Laboratory Technologist / Technician': [
    'Specimen collection/labeling',
    'Routine laboratory testing',
    'Basic instrument operation',
    'Simple culture inoculation',
    'Automated analyzer operation',
    'Blood count measurement',
    'Urinalysis/immunological screening',
    'Data entry/results',
    'Protocol adherence',
    'Basic quality control',
    'Abnormal result reporting',
    'Reagent stock maintenance',
    'Workstation disinfection',
    'Safety compliance',
    'New staff training',
    'Specimen transport/storage',
    'Other'
  ],
  'Cytotechnologist / Cytogenetic Technologist': [
    'Specimen adequacy verification',
    'Slide preparation/staining',
    'Gynecologic cytology screening',
    'Malignant cell detection',
    'Suspicious cell marking',
    'Preliminary diagnostic impression',
    'Quality control checks',
    'Specimen handling records',
    'Cell culture/harvest',
    'Metaphase preparation/banding',
    'Chromosomal abnormality analysis',
    'Karyotype charting',
    'Molecular cytogenetic assays',
    'Standardized result interpretation',
    'Abnormal result reporting',
    'Equipment calibration/maintenance',
    'Safety/regulatory compliance',
    'Training/quality assurance',
    'Other'
  ],
  'Dramatherapist': [
    'Drama therapy assessment',
    'Treatment plan implementation',
    'Safe therapeutic environment',
    'Symbolic self-expression',
    'Emotional regulation support',
    'Improvisation/theater games',
    'Behavioral experimentation',
    'Progress documentation',
    'Multidisciplinary collaboration',
    'Drama-based psychoeducation',
    'Group therapy facilitation',
    'Trauma/illness processing',
    'Crisis intervention',
    'Professional supervision/training',
    'Confidentiality/ethical boundaries',
    'Other'
  ],
  'Exercise Physiologist': [
    'History review',
    'Fitness assessment',
    'Exercise stress testing',
    'Vital signs monitoring',
    'Test analysis',
    'Exercise prescription',
    'Chronic disease rehab',
    'Supervised training',
    'Equipment instruction',
    'Behavior counseling',
    'Progress modification',
    'Multidisciplinary collaboration',
    'Patient education',
    'Record maintenance',
    'Emergency response',
    'Research participation',
    'Other'
  ],
  'Massage Therapist': [
    'Therapeutic massage',
    'Pain relief',
    'Deep tissue',
    'Neuromuscular therapy',
    'Trigger point therapy',
    'Manual lymphatic drainage',
    'Pre/post-surgical massage',
    'Oncology massage',
    'Stress management',
    'Sports rehab',
    'Headache treatment',
    'Range-of-motion stretching',
    'Prenatal massage',
    'Reflexology',
    'Self-care education',
    'Treatment documentation',
    'Other'
  ],
  'Medical Laboratory Professional (Microbiologist, Immunologist, etc.)': [
    'Specimen processing',
    'Routine/specialized testing',
    'Hematology analysis',
    'Biochemical analysis',
    'Serological testing',
    'Pathogen isolation/culture',
    'Antimicrobial susceptibility',
    'Parasite detection',
    'Molecular diagnostics',
    'Immunologic assays',
    'Quality control/calibration',
    'Result troubleshooting',
    'Result reporting',
    'Infection control surveillance',
    'Record maintenance',
    'Biosafety adherence',
    'Outbreak monitoring',
    'Transfusion testing',
    'Specimen collection',
    'Staff training/supervision',
    'Audit participation',
    'Other'
  ],
  'Medical Sonographer': [
    'Abdominal/vascular ultrasound',
    'Special ultrasound scans',
    'Cardiac echocardiography',
    '2D/Doppler imaging',
    'Equipment optimization',
    'Structure measurement',
    'Normal/abnormal differentiation',
    'History review',
    'Machine quality checks',
    'Preliminary technical summary',
    'Image archiving',
    'Ultrasound-guided intervention',
    'Clinician collaboration',
    'Bedside ultrasound support',
    'Quality assurance participation',
    'Other'
  ],
  'Music Therapist': [
    'Music-based assessment',
    'Treatment plan development',
    'Active music therapy',
    'Receptive music therapy',
    'Pain management support',
    'Emotional/mood regulation',
    'Social communication facilitation',
    'Cognitive stimulation',
    'Motor/coordination goals',
    'Palliative/oncology support',
    'Individual/group sessions',
    'Multidisciplinary collaboration',
    'Clinical documentation',
    'Music therapy psychoeducation',
    'Bedside consultation services',
    'Other'
  ],
  'Orthotist and Prosthetist': [
    'Clinical assessment/evaluation',
    'Gait/functional assessment',
    'Prosthesis prescription/design',
    'Orthosis prescription/design',
    'Measurement/casting/scanning',
    'Modification/alignment',
    'Fitting/trial adjustment',
    'Donning/doffing training',
    'Gait/mobility training',
    'Device repair/maintenance',
    'Rehabilitation collaboration',
    'Pre/post-amputation planning',
    'Congenital/trauma support',
    'Skin care education',
    'Clinical documentation',
    'Other'
  ],
  'Osteopath': [
    'History/exam',
    'Diagnosis',
    'Osteopathic manipulative treatment (OMT)',
    'Musculoskeletal treatment',
    'Posture correction',
    'Headache relief',
    'Injury recovery',
    'Circulation enhancement',
    'Arthritis rehabilitation',
    'Ergonomic guidance',
    'Self-care education',
    'Progress monitoring',
    'Referral/co-management',
    'Holistic prevention',
    'Documentation',
    'Other'
  ],
  'Paramedic / Emergency Medical Technician (EMT)': [
    'Emergency response',
    'Rapid assessment',
    'Life support',
    'Airway management',
    'Bleeding control',
    'Fracture immobilization',
    'IV/IO access',
    'Vital signs monitoring',
    'Medical emergency management',
    'Patient lifting/transport',
    'Emergency vehicle operation',
    'Dispatch communication',
    'Pre-hospital triage',
    'Documentation',
    'Handoff report',
    'Emotional support',
    'Training participation',
    'Other'
  ],
  'Pharmacist Technician': [
    'Prescription processing',
    'Medication preparation',
    'Unit-dose packaging',
    'Compounding assistance',
    'Inventory management',
    'Cycle counting',
    'Pharmacy information system',
    'Insurance billing',
    'Medication delivery',
    'Automated dispensing filling',
    'Emergency kit stocking',
    'Error monitoring',
    'Patient information',
    'Adherence support',
    'Work area maintenance',
    'Documentation',
    'Other'
  ],
  'Podiatrist': [
    'Diagnosis/treatment',
    'Physical examination',
    'Skin/nail treatment',
    'Heel pain management',
    'Diabetic foot care',
    'Sports injury care',
    'Orthotic prescription',
    'Strapping/splinting',
    'Minor surgery',
    'Local injection',
    'Therapeutic exercise',
    'Gait advice',
    'Multidisciplinary collaboration',
    'Preventive education',
    'Wound care',
    'Referral',
    'Documentation',
    'Other'
  ],
  'Public Health / Environmental Health Inspector': [
    'Food inspection',
    'Sanitation inspection',
    'Complaint investigation',
    'Disease investigation',
    'Water quality monitoring',
    'Waste management inspection',
    'Land-use evaluation',
    'Environmental sampling',
    'Enforcement',
    'Hygiene education',
    'Infection prevention advice',
    'Emergency preparedness',
    'Recreational water monitoring',
    'Housing standards oversight',
    'Facility licensing',
    'Other'
  ],
  'Radiation Therapist': [
    'Linear accelerator operation',
    'Patient positioning',
    'Simulation/localization',
    'Treatment planning assistance',
    'Setup verification',
    'Radiation delivery',
    'Patient monitoring',
    'Treatment recording',
    'Radiation safety',
    'Patient education',
    'Psychosocial support',
    'Oncology collaboration',
    'Quality assurance',
    'Immobilization device fitting',
    'Research participation',
    'Other'
  ],
  'Rehabilitation Technician': [
    'Therapy assistance',
    'Patient transfer',
    'Equipment preparation',
    'ADL assistance',
    'Exercise support',
    'Brace/splint application',
    'Modality preparation',
    'Patient monitoring',
    'Vital signs measurement',
    'Equipment cleaning',
    'Scheduling/clerical',
    'Basic patient education',
    'Rehab program support',
    'Restorative care',
    'Other'
  ],
  'Respiratory Therapist': [
    'Pulmonary function tests',
    'Blood gas measurement',
    'Oxygen therapy',
    'Mechanical ventilation',
    'Airway management',
    'Aerosol therapy',
    'Medication delivery',
    'Airway clearance',
    'Bronchoscopy assistance',
    'Non-invasive ventilation',
    'Pulmonary rehabilitation',
    'Neonatal/pediatric respiratory care',
    'CPR/emergency response',
    'Vital signs monitoring',
    'Patient education',
    'Multidisciplinary collaboration',
    'Other'
  ],
  'Social Worker': [
    'Psychosocial assessment',
    'Emotional support',
    'Crisis intervention',
    'Coping assistance',
    'Discharge planning',
    'Community referral',
    'Mental health referral',
    'Patient advocacy',
    'Care coordination',
    'Abuse reporting',
    'Patient education',
    'Benefits counseling',
    'Bereavement support',
    'Multidisciplinary participation',
    'Care plan monitoring',
    'Documentation',
    'Other'
  ],
  'Anesthesia Technician / Anesthesiologist Assistant': [
    'Equipment preparation',
    'Anesthesia assistance',
    'Airway management',
    'Invasive line placement',
    'Vital signs monitoring',
    'Blood sampling',
    'Blood gas analysis',
    'Drug administration',
    'Temperature management',
    'Resuscitation support',
    'Regional anesthesia assistance',
    'Equipment sterilization',
    'Patient transfer',
    'Pre/post anesthesia assessment',
    'Documentation',
    'Perioperative collaboration',
    'Other'
  ],
  'Anesthetic Technologist': [
    'Equipment preparation',
    'Patient monitoring',
    'Airway management',
    'Invasive line assistance',
    'Supply management',
    'Point-of-care testing',
    'Equipment troubleshooting',
    'Emergency support',
    'Documentation',
    'Safety protocol adherence',
    'Equipment cleaning',
    'Quality assurance',
    'Medication assistance',
    'Regional anesthesia assistance',
    'Mentorship and training',
    'Other'
  ],
  'Blood‑Bank Technologist': [
    'Blood typing',
    'Cross-matching',
    'Transfusion reaction investigation',
    'Blood component processing',
    'Infectious disease testing',
    'Inventory management',
    'Specimen accessioning',
    'Instrument calibration/QC',
    'Result documentation',
    'Transfusion support',
    'Regulatory compliance',
    'Antibody identification',
    'Staff supervision',
    'Emergency release',
    'Quality assurance',
    'Other'
  ],
  'Cardiology / Vascular / Pulmonary Technologist': [
    'ECG/stress testing',
    'Echocardiography',
    'Vascular ultrasound',
    'Invasive procedure assistance',
    'Electrophysiology support',
    'Hemodynamic monitoring',
    'Parameter measurement',
    'Pacemaker/defibrillator testing',
    'Pulmonary function tests',
    'Cardiopulmonary exercise testing',
    'Patient monitoring',
    'Pre/post-procedure education',
    'Equipment calibration',
    'Documentation',
    'Clinician collaboration',
    'Other'
  ],
  'Counseling / Behavioral Health Counselor': [
    'Psychosocial assessment',
    'Diagnosis',
    'Evidence-based counseling',
    'Therapeutic modalities',
    'Treatment planning',
    'Symptom support',
    'Substance abuse counseling',
    'Crisis intervention',
    'Progress documentation',
    'Coping skills training',
    'Psychoeducation',
    'Care coordination',
    'Interprofessional collaboration',
    'Client advocacy',
    'Confidentiality maintenance',
    'Other'
  ],
  'Dental Hygienist': [
    'History review',
    'Oral examination',
    'Oral cancer screening',
    'Dental radiography',
    'Plaque/tartar removal',
    'Tooth polishing',
    'Periodontal debridement',
    'Fluoride/sealant application',
    'Oral hygiene instruction',
    'Dietary counseling',
    'Periodontal charting',
    'Treatment planning assistance',
    'Patient education',
    'Implant maintenance',
    'Infection control',
    'Clinical documentation',
    'Other'
  ],
  'Dental Assistant': [
    'Room preparation',
    'Instrument sterilization',
    'Chairside assistance',
    'Suction management',
    'Dental radiography',
    'Vital signs',
    'Dental impressions',
    'Coronal polishing',
    'Fluoride application',
    'Patient comfort',
    'Oral hygiene instruction',
    'Nitrous monitoring',
    'Infection control',
    'Emergency response',
    'Record documentation',
    'Administrative tasks',
    'Other'
  ],
  'Dental Technician': [
    'Denture fabrication',
    'Crown/bridge construction',
    'Veneer fabrication',
    'Implant abutment creation',
    'Orthodontic appliance fabrication',
    'Mouthguard fabrication',
    'Maxillofacial prosthesis',
    'Model mounting',
    'Material selection',
    'Quality finishing',
    'Design record keeping',
    'Dentist communication',
    'Equipment maintenance',
    'Inventory management',
    'Other'
  ],
  'Dialysis / Renal Technologist': [
    'Equipment setup',
    'Machine priming',
    'Dialysate preparation',
    'Vital signs monitoring',
    'Parameter monitoring',
    'Vascular access cannulation',
    'Blood flow management',
    'Anticoagulation administration',
    'Complication response',
    'Patient education',
    'Access site care',
    'Infection control',
    'Treatment documentation',
    'Machine troubleshooting',
    'Equipment maintenance',
    'Water treatment oversight',
    'Quality assurance',
    'Emergency response',
    'Nurse collaboration',
    'Dietitian coordination',
    'Psychosocial support',
    'Other'
  ],
  'Endoscopy Technologist': [
    'Patient preparation',
    'Equipment setup',
    'Procedure assistance',
    'Vital signs monitoring',
    'Patient positioning/transport',
    'Specimen collection',
    'Equipment troubleshooting',
    'Scope disinfection',
    'Calibration/maintenance',
    'Inventory management',
    'Documentation',
    'Advanced intervention assistance',
    'Motility/small-bowel support',
    'Staff training',
    'Other'
  ],
  'Forensic / Medico‑Legal Laboratory Technologist': [
    'Evidence collection',
    'Chain of custody',
    'Toxicological analysis',
    'DNA profiling',
    'Serological analysis',
    'Sexual assault processing',
    'Forensic chemistry',
    'Trace evidence analysis',
    'Instrument operation',
    'Calibration/QC',
    'Reagent preparation',
    'Forensic reporting',
    'Expert testimony',
    'Multidisciplinary collaboration',
    'Regulatory compliance',
    'Evidence storage',
    'Method validation',
    'Other'
  ],
  'Health‑Information / Medical‑Record Technician': [
    'Record compilation',
    'EHR data entry',
    'Medical coding',
    'Record review',
    'Data organization',
    'Outcome tracking',
    'Confidentiality maintenance',
    'Record auditing',
    'Record retrieval/release',
    'Billing support',
    'Record transfer',
    'EHR optimization',
    'Documentation education',
    'Access logging',
    'Other'
  ],
  'Genetic Counselor': [
    'Family history collection',
    'Risk assessment',
    'Inheritance explanation',
    'Pre-test counseling',
    'Result interpretation',
    'Implication discussion',
    'Psychosocial support',
    'Family adaptation guidance',
    'Reproductive decision guidance',
    'Referral coordination',
    'Insurance advocacy',
    'Management education',
    'Provider communication',
    'Risk documentation',
    'Research participation',
    'Other'
  ],
  'Lactation Consultant': [
    'Prenatal education',
    'Latch assessment',
    'Feeding observation',
    'Pain management',
    'Milk supply evaluation',
    'Hunger cue guidance',
    'Pumping/storage guidance',
    'Return-to-work planning',
    'High-risk infant support',
    'Weaning support',
    'Provider collaboration',
    'Clinical documentation',
    'Other'
  ],
  'Medical Assistant': [
    'Vital signs recording',
    'History taking',
    'Examination preparation',
    'Phlebotomy',
    'Basic lab testing',
    'EKG performance',
    'Medication administration',
    'Wound care',
    'Instrument sterilization',
    'EHR maintenance',
    'Appointment scheduling',
    'Referral coordination',
    'Patient check-in',
    'Billing assistance',
    'Patient education',
    'Compliance adherence',
    'Other'
  ],
  'Medical Dosimetrist': [
    'Treatment plan design',
    'Tumor/organ contouring',
    'Beam optimization',
    'Dose calculation',
    'IMRT/VMAT planning',
    'Plan documentation',
    'Quality assurance',
    'Plan communication',
    'Simulation assistance',
    'TBI planning',
    'Dosimetric measurements',
    'Physicist collaboration',
    'Plan record keeping',
    'Radiation safety',
    'Other'
  ],
  'Medical Physicist': [
    'Treatment plan design',
    'Equipment calibration',
    'Quality assurance',
    'Radiation safety',
    'Equipment commissioning',
    'Diagnostic imaging support',
    'Nuclear medicine physics',
    'Radiation protection',
    'Dosimetry calculation',
    'Beam data measurement',
    'Protocol development',
    'Safety protocol implementation',
    'Regulatory compliance',
    'Research and development',
    'Staff education',
    'Clinical consultation',
    'Problem-solving consultation',
    'Brachytherapy support',
    'Imaging optimization',
    'Radiation hazard control',
    'Teaching and training',
    'Other'
  ],
  'Medical Secretary / Administrative Health Staff': [
    'Patient greeting',
    'Appointment scheduling',
    'Patient check-in',
    'Phone management',
    'Record maintenance',
    'Record retrieval',
    'Form preparation',
    'Medical transcription',
    'Billing assistance',
    'Waiting area upkeep',
    'Calendar management',
    'Confidentiality compliance',
    'Supply ordering',
    'Basic accounting',
    'External communication',
    'Data entry',
    'Other'
  ],
  'Medical Transcriptionist': [
    'Report transcription',
    'Speech recognition editing',
    'Abbreviation expansion',
    'Report formatting',
    'Grammar/accuracy check',
    'Error flagging',
    'Record compilation',
    'EHR entry',
    'Confidentiality maintenance',
    'Record revision',
    'Correspondence support',
    'Other'
  ],
  'Mental‑Health / Behavioral‑Health Counselor': [
    'Mental health assessment',
    'Individual/group counseling',
    'Diagnosis/management',
    'Evidence-based therapy',
    'Anxiety/depression support',
    'Substance abuse counseling',
    'Crisis intervention',
    'Treatment planning',
    'Coping skills training',
    'Psychoeducation',
    'Multidisciplinary collaboration',
    'Referral coordination',
    'Clinical documentation',
    'Patient advocacy',
    'Confidentiality maintenance',
    'Other'
  ],
  'Operating Department Practitioner / Surgical Technologist': [
    'Theatre preparation',
    'Sterile field maintenance',
    'Anaesthesia assistance',
    'Patient positioning',
    'Instrument passing',
    'Surgical assistance',
    'Count management',
    'Vital signs monitoring',
    'Specimen handling',
    'Wound closure assistance',
    'Post-anaesthesia monitoring',
    'Patient transfer',
    'Inventory management',
    'Equipment troubleshooting',
    'Documentation',
    'Other'
  ],
  'Physician Assistant / Associate': [
    'History taking',
    'Physical examination',
    'Illness evaluation',
    'Differential diagnosis',
    'Test ordering',
    'Treatment planning',
    'Medication prescription',
    'Procedural assistance',
    'Minor surgery',
    'Patient education',
    'Preventive counseling',
    'Referral coordination',
    'Clinical documentation',
    'Team participation',
    'Interprofessional collaboration',
    'Setting-based practice',
    'Other'
  ],
  'Sanitary / Infection‑Control Inspector': [
    'Facility inspection',
    'Hand hygiene monitoring',
    'Water/ventilation inspection',
    'Infectious waste evaluation',
    'IPC practice assessment',
    'Protocol review',
    'PPE observation',
    'Outbreak investigation',
    'Environmental sampling',
    'Corrective recommendations',
    'Staff training',
    'Regulation enforcement',
    'Citation issuance',
    'Record maintenance',
    'IPC collaboration',
    'Other'
  ],
  'Surgical and Anesthesia‑Related Technologist': [
    'OR preparation',
    'Instrument sterilization',
    'Patient positioning',
    'Sterile field maintenance',
    'Surgical counts',
    'Intraoperative assistance',
    'Anesthesia setup',
    'Airway assistance',
    'Vital signs monitoring',
    'Bleeding control',
    'Emergency support',
    'Wound closure assistance',
    'Patient transport',
    'Equipment cleaning',
    'Device troubleshooting',
    'Documentation',
    'Other'
  ],
  'Urology / Renal Technologist': [
    'Patient preparation',
    'Procedure assistance',
    'Urodynamic testing',
    'Endoscopic support',
    'ESWL assistance',
    'Equipment operation',
    'Specimen collection',
    'Dialysis assistance',
    'Vital signs monitoring',
    'Dialysis machine setup',
    'Transplant support',
    'Patient education',
    'Sterile field maintenance',
    'Test documentation',
    'Procedure scheduling',
    'Team collaboration',
    'Other'
  ],
  'Specialist Nurse': [
    'Nursing assessment',
    'Care planning',
    'Advanced interventions',
    'Medication administration',
    'Diagnostic procedures',
    'Care coordination',
    'Patient education',
    'Self-management support',
    'Staff supervision',
    'Policy development',
    'Quality improvement',
    'Clinical research',
    'Multidisciplinary liaison',
    'Expert consultation',
    'Patient advocacy',
    'Discharge planning',
    'Service development',
    'Other'
  ],
  'Fitness Therapist': [
    'Health risk assessment',
    'Medical history review',
    'Vital signs measurement',
    'Body composition analysis',
    'VO₂ testing',
    'Aerobic capacity',
    'Strength testing',
    'Flexibility testing',
    'Functional movement screen',
    'Gait analysis',
    'Balance assessment',
    'Posture analysis',
    'Cardiac rehabilitation',
    'Post‑MI exercise',
    'Hypertension management',
    'Diabetes exercise program',
    'Metabolic syndrome training',
    'Arthritis exercise',
    'Joint replacement rehab',
    'Back pain program',
    'Core stabilization',
    'Cancer recovery fitness',
    'Oncology exercise',
    'Weight management',
    'Nutrition counseling',
    'Lifestyle coaching',
    'Personal training',
    'Medical personal training',
    'Small‑group clinical exercise',
    'Low‑impact cardio',
    'Falls prevention',
    'Balance training',
    'Functional fitness',
    'Physical therapy',
    'Sports injury rehab',
    'Aquatic therapy',
    'Hydro‑rehab',
    'Sports performance',
    'Strength conditioning',
    'Agility training',
    'Worksite wellness',
    'Biometric screening',
    'Pre‑habilitation program',
    'Pre‑surgical exercise',
    'Community wellness',
    'Blood pressure reduction',
    'Stress reduction exercise',
    'Yoga therapy',
    'Tai chi',
    'Mindfulness training',
    'Post‑rehab conditioning',
    'Chronic disease management',
    'Exercise prescription',
    'Supervised exercise',
    'Treadmill stress test (in some centers)',
    'Pulmonary rehabilitation (if co‑located)',
    'Fall risk screening',
    'Gait retraining',
    'Resistance training prescription',
    'Warm‑up/cool‑down instruction',
    'Injury prevention education',
    'Adherence counseling',
    'Other'
  ],
  'Biotech Engineer': [
    'Device Calibration',
    'Bio-instrumentation Repair',
    'Medical Software Integration',
    'Quality Compliance Audit',
    'Technical Systems Training',
    'Preventive maintenance',
    'Corrective repair',
    'Sales equipment',
    'Rent equipment',
    'Calibration and testing',
    'Equipment safety checks',
    'Troubleshooting malfunctions',
    'Component replacement',
    'Risk management',
    'Regulatory compliance',
    'Staff training',
    'Vendor negotiation',
    'System integration (HIS/EMR)',
    'Equipment installations',
    'Electrical safety verification',
    'Water Quality Management',
    'Other'
  ]
};

export const CURRENCIES = [
  { value: 'USD', label: '$ (USD) - US Dollar' },
  { value: 'NGN', label: '₦ (NGN) - Nigerian Naira' },
  { value: 'GBP', label: '£ (GBP) - British Pound' },
  { value: 'EUR', label: '€ (EUR) - Euro' },
  { value: 'CAD', label: '$ (CAD) - Canadian Dollar' },
  { value: 'GHS', label: '₵ (GHS) - Ghanaian Cedi' },
  { value: 'KES', label: 'Sh (KES) - Kenyan Shilling' },
  { value: 'ZAR', label: 'R (ZAR) - South African Rand' },
  { value: 'ZMW', label: 'ZK (ZMW) - Zambian Kwacha' },
  { value: 'RWF', label: 'FRw (RWF) - Rwandan Franc' },
  { value: 'UGX', label: 'USh (UGX) - Ugandan Shilling' },
  { value: 'EGP', label: '£ (EGP) - Egyptian Pound' },
  { value: 'AED', label: 'د.إ (AED) - UAE Dirham' },
];

export const USD_TO_NGN_RATE = 1600; // 1 USD = 1600 NGN

