import React, { useState, useEffect, useRef } from 'react';
import AgoraRTC, { 
  IAgoraRTCClient, 
  ICameraVideoTrack, 
  IMicrophoneAudioTrack, 
  IAgoraRTCRemoteUser
} from 'agora-rtc-sdk-ng';
import {
  Mic,
  MicOff,
  Video,
  VideoOff,
  PhoneOff,
  Share,
  Share2,
  Users,
  MessageSquare,
  Hand,
  X,
  Maximize,
  Minimize,
  CircleDot,
  ShieldCheck
} from 'lucide-react';
import { complianceApi } from '@/services/complianceApi';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { VideoConference, VideoConferenceParticipant } from '@/types/videoConferences';
import { VideoConferenceWebSocket } from '@/services/videoConferenceWebSocket';
import { toast } from 'sonner';

interface VideoConferenceRoomProps {
  conference: VideoConference;
  ws: VideoConferenceWebSocket | null;
  onLeave: () => void;
  userId: string;
}

// AGORA CONFIGURATION
const AGORA_APP_ID = "54913c13db4b4272a0ef9b38d9e74298"; // Production App ID provided by user

export const VideoConferenceRoom: React.FC<VideoConferenceRoomProps> = ({
  conference,
  ws,
  onLeave,
  userId
}) => {
  const [isMuted, setIsMuted] = useState(false);
  const [isVideoEnabled, setIsVideoEnabled] = useState(true);
  const [isScreenSharing, setIsScreenSharing] = useState(false);
  const [isHandRaised, setIsHandRaised] = useState(false);
  const [participants, setParticipants] = useState<VideoConferenceParticipant[]>(conference.participants || []);
  const [chatMessages, setChatMessages] = useState<any[]>([]);
  const [showChat, setShowChat] = useState(false);
  const [showParticipants, setShowParticipants] = useState(false);
  const [isFullscreen, setIsFullscreen] = useState(false);
  const [chatInput, setChatInput] = useState('');
  const [isRecording, setIsRecording] = useState(conference.isRecording);
  const [showConsentModal, setShowConsentModal] = useState(false);
  const [hasConsented, setHasConsented] = useState(false);
  const [recordingRequester, setRecordingRequester] = useState<string | null>(null);

  // Agora State
  const [client, setClient] = useState<IAgoraRTCClient | null>(null);
  const [localTracks, setLocalTracks] = useState<{
    videoTrack: ICameraVideoTrack | null;
    audioTrack: IMicrophoneAudioTrack | null;
  }>({ videoTrack: null, audioTrack: null });
  const [remoteUsers, setRemoteUsers] = useState<IAgoraRTCRemoteUser[]>([]);

  const localVideoRef = useRef<HTMLDivElement>(null);
  const chatEndRef = useRef<HTMLDivElement>(null);

  // AGORA INITIALIZATION
  useEffect(() => {
    const initAgora = async () => {
      const agoraClient = AgoraRTC.createClient({ mode: 'rtc', codec: 'vp8' });
      setClient(agoraClient);

      // Agora Event Listeners
      agoraClient.on('user-published', async (user, mediaType) => {
        await agoraClient.subscribe(user, mediaType);
        if (mediaType === 'video') {
          setRemoteUsers(prev => [...prev.filter(u => u.uid !== user.uid), user]);
        }
        if (mediaType === 'audio') {
          user.audioTrack?.play();
        }
      });

      agoraClient.on('user-unpublished', (user) => {
        setRemoteUsers(prev => prev.filter(u => u.uid !== user.uid));
      });

      try {
        // Join Channel
        // Note: In production, 'null' should be replaced by a token generated by the backend
        const uid = await agoraClient.join(AGORA_APP_ID, conference.id, null, userId);
        console.log("Joined Agora channel:", conference.id, "as UID:", uid);

        // Create and Publish Local Tracks
        const [audioTrack, videoTrack] = await AgoraRTC.createMicrophoneAndCameraTracks();
        setLocalTracks({ videoTrack, audioTrack });

        if (videoTrack && localVideoRef.current) {
          videoTrack.play(localVideoRef.current);
        }
        
        await agoraClient.publish([audioTrack, videoTrack]);
        toast.success("Connected to Agora Video Network");

      } catch (error) {
        console.error('Agora initialization failed:', error);
        toast.error("Failed to connect to video network. Please check your Agora App ID.");
      }
    };

    if (conference.id && userId) {
      initAgora();
    }

    return () => {
      // Cleanup on unmount
      localTracks.videoTrack?.stop();
      localTracks.videoTrack?.close();
      localTracks.audioTrack?.stop();
      localTracks.audioTrack?.close();
      client?.leave();
    };
  }, [conference.id, userId]);

  // WebSocket event handlers (Metadata syncing)
  useEffect(() => {
    if (!ws) return;

    ws.on('participant_joined', (data) => {
      setParticipants(prev => [...prev.filter(p => p.id !== data.participant.id), data.participant]);
    });

    ws.on('participant_left', (data) => {
      setParticipants(prev => prev.filter(p => p.id !== data.participantId));
    });

    ws.on('participant_mute_changed', (data) => {
      setParticipants(prev =>
        prev.map(p =>
          p.id === data.participantId
            ? { ...p, isMicrophoneEnabled: !data.isMuted }
            : p
        )
      );
    });

    ws.on('participant_video_changed', (data) => {
      setParticipants(prev =>
        prev.map(p =>
          p.id === data.participantId
            ? { ...p, isCameraEnabled: data.isVideoEnabled }
            : p
        )
      );
    });

    ws.on('chat_message', (data) => {
      setChatMessages(prev => [...prev, data]);
    });

    ws.on('hand_raised', (data) => {
      setParticipants(prev =>
        prev.map(p =>
          p.id === data.participantId
            ? { ...p, isHandRaised: data.isRaised }
            : p
        )
      );
    });

    ws.on('recording_requested', (data) => {
      setRecordingRequester(data.requesterName);
      setShowConsentModal(true);
    });

    ws.on('recording_status_changed', (data) => {
      setIsRecording(data.isRecording);
      if (data.isRecording) {
        toast.success("Recording started - Consent verified.");
      } else {
        toast.info("Recording stopped.");
      }
    });

    return () => {
      ws.off('participant_joined');
      ws.off('participant_left');
      ws.off('participant_mute_changed');
      ws.off('participant_video_changed');
      ws.off('chat_message');
      ws.off('hand_raised');
    };
  }, [ws]);

  const toggleMute = async () => {
    const newMuteState = !isMuted;
    setIsMuted(newMuteState);
    if (localTracks.audioTrack) {
      await localTracks.audioTrack.setEnabled(!newMuteState);
    }
    if (ws) {
      ws.toggleMute(conference.id, newMuteState);
    }
  };

  const toggleVideo = async () => {
    const newVideoState = !isVideoEnabled;
    setIsVideoEnabled(newVideoState);
    if (localTracks.videoTrack) {
      await localTracks.videoTrack.setEnabled(newVideoState);
    }
    if (ws) {
      ws.toggleVideo(conference.id, newVideoState);
    }
  };

  const toggleScreenShare = () => {
    toast.info("Screen sharing integration with Agora coming soon");
    // Implementation would involve switching tracks to AgoraRTC.createScreenVideoTrack()
  };

  const toggleHandRaise = () => {
    const newHandState = !isHandRaised;
    setIsHandRaised(newHandState);
    if (ws) {
      ws.raiseHand(conference.id, newHandState);
    }
  };

  const sendChatMessage = () => {
    if (chatInput.trim() && ws) {
      ws.sendChatMessage(conference.id, chatInput.trim());
      setChatInput('');
    }
  };

  const handleKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter') {
      sendChatMessage();
    }
  };

  const handleStartRecording = () => {
    if (ws) {
      ws.requestRecording(conference.id);
      toast.info("Recording request sent to all participants.");
    }
  };

  const handleConsent = async (granted: boolean) => {
    setHasConsented(granted);
    setShowConsentModal(false);
    
    await complianceApi.logAction('RECORDING_CONSENT_GIVEN', 'VIDEO_CONFERENCE', {
        conferenceId: conference.id,
        consentGiven: granted,
        participantId: userId
    });

    if (ws) {
      ws.sendRecordingConsentResponse(conference.id, userId, granted);
    }
  };

  const toggleFullscreen = () => {
    if (!document.fullscreenElement) {
      document.documentElement.requestFullscreen();
      setIsFullscreen(true);
    } else {
      document.exitFullscreen();
      setIsFullscreen(false);
    }
  };

  const getParticipantInitials = (name: string) => {
    return name.split(' ').map(n => n[0]).join('').toUpperCase();
  };

  return (
    <div className={`fixed inset-0 bg-black text-white z-50 pt-12 sm:pt-4 safe-area-pt ${isFullscreen ? 'p-0' : 'p-4'}`}>
      {/* Header */}
      <div className="flex items-center justify-between mb-4 px-4">
        <div className="flex items-center gap-4">
          <h1 className="text-xl font-black uppercase tracking-tight text-white">{conference.title}</h1>
          <Badge className="bg-green-500 text-white border-none font-bold uppercase text-[10px] animate-pulse">
            LIVE - AGORA
          </Badge>
          {conference.isRecording && (
            <Badge className="bg-red-500 text-white border-none font-bold uppercase text-[10px] animate-pulse">
              REC
            </Badge>
          )}
        </div>

        <div className="flex items-center gap-2">
          <Button
            variant="ghost"
            size="sm"
            onClick={() => setShowParticipants(!showParticipants)}
            className="text-white hover:bg-white/10 font-bold uppercase text-[10px]"
          >
            <Users className="h-4 w-4 mr-2" />
            {participants.length}
          </Button>

          <Button
            variant="ghost"
            size="sm"
            onClick={() => setShowChat(!showChat)}
            className="text-white hover:bg-white/10 font-bold uppercase text-[10px]"
          >
            <MessageSquare className="h-4 w-4 mr-2" />
            Chat
          </Button>

          <Button
            variant="ghost"
            size="sm"
            onClick={toggleFullscreen}
            className="text-white hover:bg-white/10"
          >
            {isFullscreen ? <Minimize className="h-4 w-4" /> : <Maximize className="h-4 w-4" />}
          </Button>

          <Button
            variant="ghost"
            size="sm"
            onClick={onLeave}
            className="text-white hover:bg-red-600 rounded-full"
          >
            <X className="h-4 w-4" />
          </Button>
        </div>
      </div>

      <div className="flex h-[calc(100vh-160px)] gap-4 px-4 overflow-hidden">
        {/* Main Video Area */}
        <div className="flex-1 relative flex flex-col min-h-0">
          <div className="flex-1 overflow-y-auto custom-scrollbar min-h-0 pb-20">
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 h-fit">
              {/* Local Video Card */}
              <div className="relative bg-slate-900 rounded-[32px] overflow-hidden aspect-video shadow-2xl border border-slate-800 ring-4 ring-blue-500/20">
                <div ref={localVideoRef} className="w-full h-full object-cover" />
                <div className="absolute bottom-4 left-4 flex items-center gap-2 bg-black/40 backdrop-blur-md px-4 py-2 rounded-2xl border border-white/10">
                  <span className="text-xs font-black uppercase tracking-tight">You (Host)</span>
                  {isMuted && <MicOff className="h-3 w-3 text-red-500" />}
                </div>
              </div>

              {/* Remote Participants from Agora */}
              {remoteUsers.map((user) => {
                const participantMetadata = participants.find(p => p.id === user.uid || p.userId === user.uid);
                return (
                  <div key={user.uid} className="relative bg-slate-900 rounded-[32px] overflow-hidden aspect-video shadow-xl border border-slate-800">
                    <div 
                      ref={(node) => user.videoTrack?.play(node as HTMLDivElement)} 
                      className="w-full h-full object-cover" 
                    />
                    {!user.hasVideo && (
                      <div className="absolute inset-0 flex items-center justify-center bg-slate-800">
                        <div className="w-20 h-20 bg-blue-600 rounded-full flex items-center justify-center text-white text-2xl font-black shadow-2xl">
                          {participantMetadata?.userName ? getParticipantInitials(participantMetadata.userName) : '?'}
                        </div>
                      </div>
                    )}
                    <div className="absolute bottom-4 left-4 flex items-center gap-2 bg-black/40 backdrop-blur-md px-4 py-2 rounded-2xl border border-white/10">
                      <span className="text-xs font-black uppercase tracking-tight">
                        {participantMetadata?.userName || `Participant ${user.uid}`}
                      </span>
                      {!user.hasAudio && <MicOff className="h-3 w-3 text-red-500" />}
                    </div>
                  </div>
                );
              })}
            </div>
          </div>

          {/* Floating Controls */}
          <div className="absolute bottom-8 left-1/2 transform -translate-x-1/2 z-50">
            <div className="flex items-center gap-4 bg-slate-900/80 backdrop-blur-2xl rounded-[32px] px-8 py-4 border border-white/10 shadow-premium">
              <Button
                variant="ghost"
                onClick={toggleMute}
                className={`w-14 h-14 rounded-2xl ${isMuted ? 'bg-red-500 text-white hover:bg-red-600' : 'bg-slate-800 text-white hover:bg-slate-700'}`}
              >
                {isMuted ? <MicOff className="h-6 w-6" /> : <Mic className="h-6 w-6" />}
              </Button>

              <Button
                variant="ghost"
                onClick={toggleVideo}
                className={`w-14 h-14 rounded-2xl ${!isVideoEnabled ? 'bg-red-500 text-white hover:bg-red-600' : 'bg-slate-800 text-white hover:bg-slate-700'}`}
              >
                {isVideoEnabled ? <Video className="h-6 w-6" /> : <VideoOff className="h-6 w-6" />}
              </Button>

              <Button
                variant="ghost"
                onClick={toggleScreenShare}
                className="w-14 h-14 rounded-2xl bg-slate-800 text-white hover:bg-slate-700"
              >
                <Share className="h-6 w-6" />
              </Button>

              <Button
                variant="ghost"
                onClick={toggleHandRaise}
                className={`w-14 h-14 rounded-2xl ${isHandRaised ? 'bg-yellow-500 text-white' : 'bg-slate-800 text-white'}`}
              >
                <Hand className="h-6 w-6" />
              </Button>

              <div className="w-px h-10 bg-white/10 mx-2" />

              <Button
                variant="ghost"
                onClick={handleStartRecording}
                className={`w-14 h-14 rounded-2xl ${isRecording ? 'bg-red-600 text-white animate-pulse' : 'bg-slate-800 text-white hover:bg-slate-700'}`}
              >
                <CircleDot className="h-6 w-6" />
              </Button>

              <div className="w-px h-10 bg-white/10 mx-2" />

              <Button
                onClick={onLeave}
                className="w-14 h-14 rounded-2xl bg-red-600 text-white hover:bg-red-700 shadow-lg shadow-red-500/20"
              >
                <PhoneOff className="h-6 w-6" />
              </Button>
            </div>
          </div>
        </div>

        {/* Unified Sidebar */}
        <div className={`w-96 bg-white/5 backdrop-blur-xl rounded-[40px] border border-white/10 flex flex-col min-h-0 ${showChat || showParticipants ? 'block' : 'hidden'}`}>
          <div className="flex p-2 gap-2 border-b border-white/10">
            <button
              onClick={() => { setShowParticipants(true); setShowChat(false); }}
              className={`flex-1 py-4 rounded-[28px] text-[11px] font-black uppercase tracking-widest transition-all ${showParticipants ? 'bg-blue-600 text-white shadow-lg' : 'text-slate-400 hover:text-white'}`}
            >
              Participants ({participants.length})
            </button>
            <button
              onClick={() => { setShowChat(true); setShowParticipants(false); }}
              className={`flex-1 py-4 rounded-[28px] text-[11px] font-black uppercase tracking-widest transition-all ${showChat ? 'bg-blue-600 text-white shadow-lg' : 'text-slate-400 hover:text-white'}`}
            >
              Consultation Chat
            </button>
          </div>

          <div className="flex-1 overflow-hidden min-h-0">
            {showParticipants && (
              <div className="p-6 space-y-4 overflow-y-auto h-full custom-scrollbar">
                {participants.map((participant) => (
                  <div key={participant.id} className="flex items-center gap-4 bg-white/5 p-4 rounded-3xl border border-white/5">
                    <div className="w-10 h-10 bg-blue-600/20 rounded-2xl flex items-center justify-center text-blue-400 text-sm font-black">
                      {getParticipantInitials(participant.userName)}
                    </div>
                    <div className="flex-1">
                      <div className="flex items-center gap-2">
                        <span className="text-sm font-black uppercase tracking-tight text-white">{participant.userName}</span>
                        {participant.isHost && (
                          <Badge className="bg-blue-600 text-white border-none text-[8px] font-bold">HOST</Badge>
                        )}
                      </div>
                      <div className="flex items-center gap-2 mt-1">
                        <div className={`w-1.5 h-1.5 rounded-full ${participant.connectionStatus === 'connected' ? 'bg-green-500' : 'bg-red-500'}`} />
                        <span className="text-[10px] font-bold text-slate-500 uppercase tracking-widest">{participant.connectionStatus}</span>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            )}

            {showChat && (
              <div className="flex flex-col h-full">
                <div className="flex-1 p-6 overflow-y-auto space-y-4 custom-scrollbar">
                  {chatMessages.map((msg, idx) => (
                    <div key={idx} className="space-y-1">
                      <p className="text-[10px] font-black text-blue-400 uppercase tracking-widest">{msg.userId}</p>
                      <div className="bg-white/5 p-4 rounded-2xl border border-white/5 text-sm text-slate-200 font-bold leading-relaxed">
                        {msg.message}
                      </div>
                    </div>
                  ))}
                  <div ref={chatEndRef} />
                </div>

                <div className="p-6 border-t border-white/10 bg-black/20">
                  <div className="flex gap-3">
                    <input
                      type="text"
                      value={chatInput}
                      onChange={(e) => setChatInput(e.target.value)}
                      onKeyPress={handleKeyPress}
                      placeholder="Type a message..."
                      className="flex-1 bg-white/5 border border-white/10 rounded-2xl px-6 py-3 text-sm text-white focus:outline-none focus:border-blue-500 transition-all font-bold"
                    />
                    <Button
                      onClick={sendChatMessage}
                      className="bg-blue-600 hover:bg-blue-700 rounded-2xl px-6"
                    >
                      <MessageSquare className="h-4 w-4" />
                    </Button>
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>

      <Dialog open={showConsentModal} onOpenChange={setShowConsentModal}>
        <DialogContent className="bg-slate-900 border border-white/10 text-white rounded-[40px] max-w-md">
          <DialogHeader>
            <div className="w-16 h-16 bg-blue-600/20 rounded-[24px] flex items-center justify-center mb-6 mx-auto">
              <ShieldCheck className="h-8 w-8 text-blue-400" />
            </div>
            <DialogTitle className="text-2xl font-black uppercase tracking-tight text-center">Recording Consent Required</DialogTitle>
            <DialogDescription className="text-slate-400 text-center font-bold leading-relaxed pt-4">
              {recordingRequester} has requested to record this clinical consultation for medical documentation purposes. 
              <br/><br/>
              Under HIPAA and medical data privacy regulations, all participants must provide explicit consent before recording begins.
            </DialogDescription>
          </DialogHeader>
          <DialogFooter className="flex flex-col sm:flex-row gap-4 mt-8 pt-6 border-t border-white/5">
            <Button
              variant="ghost"
              onClick={() => handleConsent(false)}
              className="flex-1 rounded-2xl border border-white/10 text-slate-400 hover:text-white hover:bg-white/5 font-black uppercase text-xs tracking-widest py-6"
            >
              Decline
            </Button>
            <Button
              onClick={() => handleConsent(true)}
              className="flex-1 rounded-2xl bg-blue-600 hover:bg-blue-700 text-white shadow-lg shadow-blue-600/20 font-black uppercase text-xs tracking-widest py-6"
            >
              I Consent
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
};
