// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ywsznjcenfqmyeszwivk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3c3puamNlbmZxbXllc3p3aXZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcwMjk1NjYsImV4cCI6MjA5MjYwNTU2Nn0.mf1MIGVnIgkhOG5KcOBpaN7xcTzeUwiYzJ6cpWVOua8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  realtime: {
    // Disable real-time to prevent WebSocket errors during migration
    params: {
      eventsPerSecond: 0,
    },
  },
});

// Safe real-time subscription function that prevents WebSocket errors
export const safeRealtimeSubscription = (table: string, callback: (payload: any) => void) => {
  try {
    const channel = supabase
      .channel(`safe_${table}`)
      .on(
        'postgres_changes',
        {
          event: 'INSERT',
          schema: 'public',
          table: table
        },
        callback
      )
      .subscribe();

    return () => {
      try {
        supabase.removeChannel(channel);
      } catch (error) {
        console.warn('Error removing Supabase channel:', error);
      }
    };
  } catch (error) {
    console.error('Error setting up Supabase real-time subscription:', error);
    return () => {}; // Return empty cleanup function
  }
};